# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import music_player.player_state as module_0
import music_player.player_seek as module_1


def test_case_0():
    bytes_0 = b"\xff1\x0c="
    bool_0 = True
    dict_0 = {}
    list_0 = [bytes_0, dict_0]
    bytes_1 = b"Z\xce\xfe\xafz\xbd\xcd"
    list_1 = [list_0, bytes_1, bool_0]
    player_state_0 = module_0.PlayerState(list_1, bytes_0)
    module_1.get_progress(player_state_0)


def test_case_1():
    bool_0 = False
    player_state_0 = module_0.PlayerState(bool_0, bool_0)
    str_0 = module_1.render_progress_bar(player_state_0)
    assert str_0 == "[Time null]"


def test_case_2():
    bool_0 = False
    set_0 = set()
    player_state_0 = module_0.PlayerState(bool_0, set_0)
    module_1.seek_to(player_state_0, set_0)


def test_case_3():
    bool_0 = False
    player_state_0 = module_0.PlayerState(bool_0, bool_0)
    module_1.nudge(player_state_0, bool_0)
    str_0 = module_1.render_progress_bar(player_state_0)
    assert str_0 == "[Time null]"


def test_case_4():
    bool_0 = False
    player_state_0 = module_0.PlayerState(bool_0, bool_0)
    module_1.seek_to(player_state_0, bool_0)
    tuple_0 = module_1.get_progress(player_state_0)
    player_state_1 = module_0.PlayerState(tuple_0, bool_0)
    module_1.nudge(player_state_1, bool_0)


def test_case_5():
    bool_0 = False
    player_state_0 = module_0.PlayerState(bool_0, bool_0)
    tuple_0 = module_1.get_progress(player_state_0)
    none_type_0 = None
    player_state_1 = module_0.PlayerState(tuple_0, bool_0)
    module_1.seek_to(player_state_0, none_type_0)
    module_1.seek_to(player_state_1, tuple_0)
