# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
import pytest
import music_player.player_state as module_0
import music_player.player_seek as module_1


# Test: checking if the system can calculate progress even if the data is unclear (nested lists and bytes)
def test_case_0():
    bytes_0 = b"\xff1\x0c="
    bool_0 = True
    dict_0 = {}
    list_0 = [bytes_0, dict_0]
    bytes_1 = b"Z\xce\xfe\xafz\xbd\xcd"
    list_1 = [list_0, bytes_1, bool_0]
    player_state_0 = module_0.PlayerState(list_1, bytes_0)
    module_1.get_progress(player_state_0)


# Test: ensuring the progress bar shows "[Time null]" correctly when the player hasn't started
def test_case_1():
    bool_0 = False
    player_state_0 = module_0.PlayerState(bool_0, bool_0)
    str_0 = module_1.render_progress_bar(player_state_0)
    assert str_0 == "[Time null]"


# Test: verifying that the skip/seek function doesn't crash if it receives a 'set' of data
def test_case_2():
    bool_0 = False
    set_0 = set()
    player_state_0 = module_0.PlayerState(bool_0, set_0)
    module_1.seek_to(player_state_0, set_0)


# Test: ensuring that moving the playhead on an empty state still results in a "[Time null]" display
def test_case_3():
    bool_0 = False
    player_state_0 = module_0.PlayerState(bool_0, bool_0)
    module_1.nudge(player_state_0, bool_0)
    str_0 = module_1.render_progress_bar(player_state_0)
    assert str_0 == "[Time null]"


# Test: checking if seeking with a True/False value followed by a nudge causes any errors
def test_case_4():
    bool_0 = False
    player_state_0 = module_0.PlayerState(bool_0, bool_0)
    module_1.seek_to(player_state_0, bool_0)
    tuple_0 = module_1.get_progress(player_state_0)
    player_state_1 = module_0.PlayerState(tuple_0, bool_0)
    module_1.nudge(player_state_1, bool_0)


# Test: checking that the system stays stable when given 'None' or groups of data (tuples) instead of numbers
def test_case_5():
    bool_0 = False
    player_state_0 = module_0.PlayerState(bool_0, bool_0)
    tuple_0 = module_1.get_progress(player_state_0)
    none_type_0 = None
    player_state_1 = module_0.PlayerState(tuple_0, bool_0)
    module_1.seek_to(player_state_0, none_type_0)
    module_1.seek_to(player_state_1, tuple_0)