# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
import music_player.player_time as module_0
import music_player.player_state as module_1


def test_case_0():
    bytes_0 = b"=\x0c\xbd\x19\xdc\xee\xdbP\x14"
    module_0.save_resume_state(bytes_0)


def test_case_1():
    none_type_0 = None
    module_0.load_resume_state(none_type_0)


def test_case_2():
    str_0 = "A%(=&A"
    module_0.load_resume_state(str_0)


def test_case_3():
    bytes_0 = b"m*t\xa9wLl\x8b\xf4dR\xf8H\xcf"
    module_0.set_alarm(bytes_0, bytes_0)


def test_case_4():
    bool_0 = False
    module_0.show_recently_added(bool_0)


def test_case_5():
    none_type_0 = None
    module_0.save_resume_state(none_type_0)


def test_case_6():
    str_0 = "A%(=&A"
    module_0.check_alarms(str_0)


def test_case_7():
    none_type_0 = None
    module_0.show_recently_added(none_type_0)


def test_case_8():
    none_type_0 = None
    module_0.set_alarm(none_type_0, none_type_0)


def test_case_9():
    none_type_0 = None
    module_0.cancel_alarm(none_type_0)


def test_case_10():
    none_type_0 = None
    module_0.check_alarms(none_type_0)


def test_case_11():
    none_type_0 = None
    player_state_0 = module_1.PlayerState(none_type_0, none_type_0)
    module_0.check_alarms(player_state_0)


def test_case_12():
    bytes_0 = b"p\x10\xf0"
    module_0.cancel_alarm(bytes_0)


def test_case_13():
    none_type_0 = None
    player_state_0 = module_1.PlayerState(none_type_0, none_type_0)
    module_0.show_recently_added(player_state_0)


def test_case_14():
    none_type_0 = None
    player_state_0 = module_1.PlayerState(none_type_0, none_type_0)
    module_0.save_resume_state(player_state_0)


def test_case_15():
    str_0 = "A%(=&A"
    none_type_0 = None
    module_0.set_alarm(str_0, none_type_0)
    module_0.load_resume_state(str_0)


def test_case_16():
    none_type_0 = None
    player_state_0 = module_1.PlayerState(none_type_0, none_type_0)
    module_0.cancel_alarm(player_state_0)


def test_case_17():
    bytes_0 = b"=\xbd\x19\xdc\xee"
    module_0.set_alarm(bytes_0, bytes_0)


def test_case_18():
    bytes_0 = b"=\x0c\xbd\x19\xdc\xee\xdbP\x14"
    player_state_0 = module_1.PlayerState(bytes_0, bytes_0)
    module_0.show_recently_added(player_state_0)


def test_case_19():
    bytes_0 = b"=\x0c\xbd\x19\xdc\xee\xdbP\x14"
    str_0 = "_n6>M"
    module_0.set_alarm(bytes_0, str_0)
    module_0.show_recently_added(str_0)


def test_case_20():
    bytes_0 = b"=\x0c\xbd\x19\xdc\xee\xdbP\x14"
    str_0 = "_n6>M"
    none_type_0 = module_0.set_alarm(bytes_0, str_0)
    module_0.set_alarm(str_0, none_type_0)


def test_case_21():
    str_0 = " vw6V$[8`SL6VBk\x0cs"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    module_0.save_resume_state(player_state_0)


def test_case_22():
    bytes_0 = b""
    player_state_0 = module_1.PlayerState(bytes_0, bytes_0)
    module_0.show_recently_added(player_state_0)
