# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import music_player.player_state as module_0


def test_case_0():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    assert player_state_0.current_index == 0
    assert player_state_0.position_seconds == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert player_state_0.volume == 100
    assert player_state_0.saved_volume == 100
    assert (
        f"{type(module_0.PlayerState.current_track).__module__}.{type(module_0.PlayerState.current_track).__qualname__}"
        == "builtins.property"
    )
