# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import music_player.player_state as module_0
import music_player.player_queue as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "Ia}khqS"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.next_track(player_state_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "*qFja;UFu\trIi$;4O8"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.previous_track(player_state_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "Ia}khqS"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.previous_track(player_state_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "M-h"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.previous_track(player_state_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "Jjf"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.previous_track(player_state_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = "lMr?\\w^T%Q4B"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.next_track(player_state_0)


def test_case_6():
    none_type_0 = None
    list_0 = [none_type_0]
    player_state_0 = module_0.PlayerState(list_0, list_0)
    module_1.previous_track(player_state_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    str_0 = "n0}Jot5z\rw5+c"
    none_type_0 = None
    list_0 = [str_0, str_0, str_0, none_type_0]
    player_state_0 = module_0.PlayerState(list_0, str_0)
    none_type_1 = module_1.previous_track(player_state_0)
    assert player_state_0.current_index == 3
    module_1.previous_track(player_state_0)


def test_case_8():
    none_type_0 = None
    list_0 = [none_type_0]
    player_state_0 = module_0.PlayerState(list_0, list_0)
    module_1.next_track(player_state_0)
    module_1.previous_track(player_state_0)


def test_case_9():
    none_type_0 = None
    list_0 = [none_type_0, none_type_0, none_type_0, none_type_0]
    player_state_0 = module_0.PlayerState(list_0, none_type_0)
    none_type_1 = module_1.previous_track(player_state_0)
    assert player_state_0.current_index == 3
    none_type_2 = module_1.next_track(player_state_0)
    assert player_state_0.current_index == 0


@pytest.mark.xfail(strict=True)
def test_case_10():
    str_0 = "n6Sown+#om^ad$ U lp"
    none_type_0 = None
    list_0 = [str_0, str_0, str_0, none_type_0]
    player_state_0 = module_0.PlayerState(list_0, str_0)
    none_type_1 = module_1.previous_track(player_state_0)
    assert player_state_0.current_index == 3
    module_1.next_track(player_state_0)
