# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
import pytest
import music_player.player_state as module_0
import music_player.player_audio as module_1


@pytest.mark.xfail(strict=True)
# Test: checking that using boolean (True/False) values doesn't break the volume settings
def test_case_0():
    bool_0 = True
    player_state_0 = module_0.PlayerState(bool_0, bool_0)
    module_1.change_volume(player_state_0, bool_0)


@pytest.mark.xfail(strict=True)
# Test: verifying the system handles empty lists and missing data (None) without crashing
def test_case_1():
    none_type_0 = None
    module_1.change_volume(none_type_0, none_type_0)
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    module_1.change_volume(player_state_0, list_0)
    str_0 = "4i@b4G~)\n5=K}"
    module_1.handle_mute_command(player_state_0, str_0)
    module_1.toggle_mute(player_state_0)


@pytest.mark.xfail(strict=True)
# Test: ensuring the system correctly rejects raw bytes when they are used as a player state
def test_case_2():
    bytes_0 = b"'\xa8X\xa7"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.toggle_mute(player_state_0)


# Test: checking that the volume controller fails gracefully when given byte-string data
def test_case_3():
    bytes_0 = b"\xd1{g\x8fz\xdb"
    str_0 = "w!r;"
    none_type_0 = module_1.change_volume(bytes_0, str_0)
    module_1.handle_mute_command(str_0, str_0)
    module_1.toggle_mute(none_type_0)


@pytest.mark.xfail(strict=True)
# Test: checking how the mute function handles incorrect whole numbers (integers)
def test_case_4():
    int_0 = 1131
    module_1.handle_mute_command(int_0, int_0)


# Test: verifying that the system handles multiline text and missing values safely
def test_case_5():
    none_type_0 = None
    str_0 = "v"
    module_1.handle_mute_command(none_type_0, str_0)
    str_1 = ">qnmSFut"
    player_state_0 = module_0.PlayerState(none_type_0, str_1)
    str_2 = "\n ^ Stopplaback And &ee sison toTX.P\n    SL-01.\n   C"
    str_3 = "O\tx#2\rRB\nN,/tF7Vuq"
    module_1.change_volume(str_2, str_3)
    module_1.handle_mute_command(player_state_0, str_1)


# Test: validating that audio commands still work even if the music library is empty
def test_case_6():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    str_0 = "ee"
    module_1.handle_mute_command(player_state_0, str_0)
    module_1.change_volume(player_state_0, list_0)


# Test: checking how the volume behaves with large decimal numbers and negative numbers
def test_case_7():
    int_0 = -1132
    bool_0 = True
    str_0 = "\n ^ Stopplaback And &ee sison toTX.P\n    SL-01.\n   C"
    module_1.change_volume(bool_0, int_0)
    float_0 = 3255.514816
    module_1.handle_mute_command(float_0, str_0)


@pytest.mark.xfail(strict=True)
# Test: ensuring the mute toggle still works correctly after the volume has been changed
def test_case_8():
    int_0 = 2937
    str_0 = "[kK"
    player_state_0 = module_0.PlayerState(int_0, str_0)
    module_1.change_volume(player_state_0, int_0)
    module_1.toggle_mute(player_state_0)


@pytest.mark.xfail(strict=True)
# Test: checking if the system can handle the state object being passed into its own volume logic
def test_case_9():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    none_type_0 = module_1.change_volume(player_state_0, list_0)
    module_1.toggle_mute(none_type_0)
    module_1.change_volume(player_state_0, player_state_0)


# Test: verifying that mute commands work properly when given complex string paths
def test_case_10():
    bytes_0 = b"\xd1{g\x8fz\xdb"
    str_0 = "/dvnbUTe"
    module_1.change_volume(bytes_0, str_0)
    module_1.handle_mute_command(str_0, str_0)


# Test: ensuring that empty lists are not accepted as valid settings for the mute command
def test_case_11():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    str_0 = "GxJ\\S"
    module_1.handle_mute_command(list_0, str_0)
    module_1.change_volume(player_state_0, list_0)


# Test: checking the volume logic against several rapid command inputs
def test_case_12():
    bytes_0 = b"\xd1{g\x8fz\xdb"
    str_0 = "w!r;"
    module_1.change_volume(bytes_0, str_0)
    module_1.handle_mute_command(str_0, str_0)


# Test: verifying that normal mute commands work fine when the library state is empty
def test_case_13():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    str_0 = "Nf("
    module_1.handle_mute_command(player_state_0, str_0)