# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import music_player.player_config as module_0
import enum as module_1
import re as module_2
import music_player.player_state as module_3


def test_case_0():
    none_type_0 = None
    module_0.load_settings(none_type_0)


def test_case_1():
    none_type_0 = None
    module_0.view_stats(none_type_0)


def test_case_2():
    auto_0 = module_1.auto()
    module_0.view_stats(auto_0)


def test_case_3():
    var_0 = module_2.purge()
    module_0.add_tag(var_0, var_0, var_0)


def test_case_4():
    str_0 = "|~8]0eKQ\nh"
    module_0.add_tag(str_0, str_0, str_0)


def test_case_5():
    regex_flag_0 = module_2.RegexFlag.IGNORECASE
    module_0.list_all_tags(regex_flag_0)


def test_case_6():
    none_type_0 = None
    module_0.load_settings(none_type_0)


def test_case_7():
    regex_flag_0 = module_2.RegexFlag.TEMPLATE
    str_0 = ""
    module_0.filter_by_tag(regex_flag_0, str_0)


def test_case_8():
    bool_0 = False
    module_0.add_tag(bool_0, bool_0, bool_0)


def test_case_9():
    var_0 = module_2.RegexFlag.IGNORECASE
    module_0.add_tag(var_0, var_0, var_0)


def test_case_10():
    regex_flag_0 = module_2.RegexFlag.IGNORECASE
    module_0.load_settings(regex_flag_0)


def test_case_11():
    list_0 = []
    player_state_0 = module_3.PlayerState(list_0, list_0)
    module_0.view_stats(player_state_0)
