# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import music_player.playlists_advanced as module_0
import music_player.player_state as module_1
import music_player.playlist_model as module_2


def test_case_0():
    str_0 = ""
    module_0.merge_playlists(str_0, str_0, str_0)


def test_case_1():
    str_0 = "OWq\x0cWD2"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    module_0.copy_playlist(player_state_0, str_0, str_0)
    module_0.merge_playlists(player_state_0, str_0, str_0, player_state_0)
    none_type_0 = None
    str_1 = "k$^v2Lpj\x0b{\x0bEE"
    module_0.merge_playlists(player_state_0, none_type_0, str_1)


def test_case_2():
    str_0 = "Y@wCjM"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    module_0.copy_playlist(player_state_0, str_0, str_0)


def test_case_3():
    str_0 = "0+bN9$"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    none_type_0 = module_0.merge_playlists(player_state_0, str_0, str_0)
    module_0.copy_playlist(player_state_0, str_0, none_type_0)


def test_case_4():
    str_0 = "0+bN9$"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    str_1 = "$Nhx{V"
    none_type_0 = module_0.copy_playlist(player_state_0, player_state_0, str_1)
    str_2 = "\n[Help] /_l.add <playlist> <%ibrary-index>"
    module_0.merge_playlists(none_type_0, str_2, none_type_0, player_state_0)
    module_0.merge_playlists(player_state_0, str_0, str_0)


def test_case_5():
    str_0 = ""
    module_0.merge_playlists(str_0, str_0, str_0)


def test_case_6():
    str_0 = "``ajR@H"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    module_0.merge_playlists(player_state_0, str_0, str_0)


def test_case_7():
    str_0 = "0+bN9$"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    module_0.merge_playlists(player_state_0, str_0, str_0)


def test_case_8():
    none_type_0 = None
    str_0 = "'o{uB"
    playlist_0 = module_2.Playlist(str_0)
    var_0 = playlist_0.__repr__()
    player_state_0 = module_1.PlayerState(var_0, var_0)
    var_1 = player_state_0.__repr__()
    var_2 = player_state_0.__eq__(none_type_0)
    player_state_1 = module_1.PlayerState(var_2, str_0)
    str_1 = ""
    module_0.merge_playlists(player_state_1, str_1, var_1)
    none_type_1 = None
    playlist_1 = module_2.Playlist(none_type_1)
    var_3 = playlist_1.__eq__(none_type_1)
    module_0.copy_playlist(var_3, var_1, none_type_1)
    var_4 = playlist_1.__eq__(none_type_0)
    str_2 = "#\nhElp"
    module_0.copy_playlist(var_4, none_type_1, str_2)


def test_case_9():
    str_0 = ":ml@$Xr\x0b\x0cL8r,>\x0cr|"
    playlist_0 = module_2.Playlist(str_0)
    bool_0 = True
    none_type_0 = None
    str_1 = "o^zV}1Ukd"
    player_state_0 = module_1.PlayerState(playlist_0, str_1)
    module_0.copy_playlist(player_state_0, none_type_0, str_1)
    str_2 = "\n"
    module_0.merge_playlists(bool_0, str_2, str_2, str_2)


def test_case_10():
    str_0 = "0+bN9$"
    none_type_0 = None
    str_1 = ""
    module_0.merge_playlists(none_type_0, str_0, str_1)
