# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import music_player.player_state as module_0
import music_player.player_seek as module_1
import music_player.library as module_2


def test_case_0():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    module_1.seek_to(player_state_0, player_state_0)


def test_case_1():
    bool_0 = True
    none_type_0 = None
    str_0 = "\n    S3-10: Sort playlist by 'artist', 'title', or 'duration'.\n    "
    track_0 = module_2.Track(bool_0, str_0, str_0, bool_0)
    var_0 = track_0.__eq__(none_type_0)
    player_state_0 = module_0.PlayerState(bool_0, var_0)
    int_0 = 5
    module_1.nudge(player_state_0, int_0)


def test_case_2():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    module_1.render_progress_bar(player_state_0)


def test_case_3():
    bool_0 = True
    track_0 = module_2.Track(bool_0, bool_0, duration_seconds=bool_0)
    list_0 = [track_0]
    player_state_0 = module_0.PlayerState(list_0, bool_0)
    module_1.render_progress_bar(player_state_0)


def test_case_4():
    bytes_0 = b"`\xc0\xea?D\xc4"
    none_type_0 = None
    track_0 = module_2.Track(bytes_0, none_type_0, duration_seconds=bytes_0)
    list_0 = [track_0, track_0]
    int_0 = 60
    list_1 = [track_0]
    player_state_0 = module_0.PlayerState(list_0, int_0)
    module_1.seek_to(player_state_0, list_1)


def test_case_5():
    none_type_0 = None
    track_0 = module_2.Track(none_type_0, none_type_0, duration_seconds=none_type_0)
    list_0 = [track_0, track_0]
    int_0 = 60
    list_1 = [track_0]
    player_state_0 = module_0.PlayerState(list_0, int_0)
    module_1.seek_to(player_state_0, list_1)


def test_case_6():
    none_type_0 = None
    track_0 = module_2.Track(none_type_0, none_type_0, duration_seconds=none_type_0)
    list_0 = [track_0, track_0]
    int_0 = 60
    list_1 = track_0.__eq__(track_0)
    player_state_0 = module_0.PlayerState(list_0, int_0)
    module_1.seek_to(player_state_0, list_1)


def test_case_7():
    bool_0 = False
    track_0 = module_2.Track(bool_0, bool_0, duration_seconds=bool_0)
    list_0 = [track_0]
    bool_1 = True
    player_state_0 = module_0.PlayerState(list_0, bool_1)
    module_1.render_progress_bar(player_state_0)