# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import music_player.player_shortcuts as module_0


def test_case_0():
    none_type_0 = None
    str_0 = "x0U"
    module_0.handle_keypress(none_type_0, str_0)


def test_case_1():
    none_type_0 = None
    str_0 = "x0U"
    module_0.handle_keypress(str_0, str_0)
    module_0.handle_keypress(str_0, none_type_0)


def test_case_2():
    none_type_0 = None
    str_0 = "p#+"
    module_0.handle_keypress(none_type_0, str_0)


def test_case_3():
    str_0 = "x0U"
    module_0.handle_keypress(str_0, str_0)


def test_case_4():
    str_0 = "x0U"
    str_1 = "~="
    module_0.handle_keypress(str_0, str_1)


def test_case_5():
    none_type_0 = None
    str_0 = "<ku"
    module_0.handle_keypress(none_type_0, str_0)


def test_case_6():
    str_0 = "x0U"
    str_1 = "@"
    module_0.handle_keypress(str_0, str_1)