# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import music_player.player_state as module_0
import music_player.player_queue as module_1
import music_player.library as module_2


def test_case_0():
    list_0 = []
    none_type_0 = None
    player_state_0 = module_0.PlayerState(list_0, none_type_0)
    module_1.show_queue(player_state_0)
    bool_0 = True
    none_type_1 = module_1.toggle_shuffle(bool_0)
    module_1.toggle_shuffle(none_type_1)


def test_case_1():
    bytes_0 = b"\xdc\xb4\xf8\xd4\xa6\xf3R#\xbe"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.toggle_shuffle(player_state_0)


def test_case_2():
    none_type_0 = None
    player_state_0 = module_0.PlayerState(none_type_0, none_type_0)
    str_0 = ""
    module_1.set_loop_mode(player_state_0, str_0)


def test_case_3():
    bytes_0 = b"G"
    set_0 = {bytes_0, bytes_0}
    player_state_0 = module_0.PlayerState(set_0, set_0)
    module_1.add_to_queue(set_0, set_0)
    none_type_0 = module_1.clear_queue(player_state_0)
    module_1.add_to_queue(none_type_0, set_0)


def test_case_4():
    bytes_0 = b"\x0c\xa9\x8f\n\xfb\xd98"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.add_to_queue(player_state_0, player_state_0)


def test_case_5():
    str_0 = "12a@0"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.remove_from_queue(player_state_0, str_0)


def test_case_6():
    bytes_0 = b"\xbb"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.show_queue(player_state_0)


def test_case_7():
    none_type_0 = None
    player_state_0 = module_0.PlayerState(none_type_0, none_type_0)
    module_1.show_queue(player_state_0)


def test_case_8():
    str_0 = ""
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.clear_queue(player_state_0)


def test_case_9():
    bool_0 = False
    bool_1 = False
    tuple_0 = (bool_0, bool_0, bool_1)
    module_1.toggle_shuffle(tuple_0)


def test_case_10():
    bool_0 = True
    tuple_0 = ()
    var_0 = bool_0.__repr__()
    module_1.set_loop_mode(var_0, tuple_0)


def test_case_11():
    bytes_0 = b"G"
    set_0 = {bytes_0, bytes_0}
    player_state_0 = module_0.PlayerState(set_0, set_0)
    module_1.add_to_queue(set_0, set_0)
    module_1.toggle_shuffle(player_state_0)


def test_case_12():
    none_type_0 = None
    float_0 = 1205.575014
    int_0 = 2297
    track_0 = module_2.Track(int_0, float_0)
    list_0 = [track_0, track_0, track_0, track_0, track_0]
    player_state_0 = module_0.PlayerState(list_0, none_type_0)
    str_0 = "-r_>~"
    none_type_1 = module_1.remove_from_queue(player_state_0, str_0)
    track_1 = module_2.Track(float_0, float_0)
    var_0 = track_1.__repr__()
    player_state_1 = module_0.PlayerState(var_0, none_type_1)
    module_1.next_track(player_state_1)


def test_case_13():
    none_type_0 = None
    module_1.play_next(none_type_0, none_type_0)


def test_case_14():
    none_type_0 = None
    none_type_1 = module_1.play_next(none_type_0, none_type_0)
    none_type_2 = module_1.clear_queue(none_type_0)
    none_type_3 = module_1.clear_queue(none_type_0)
    module_1.add_to_queue(none_type_2, none_type_1)
    dict_0 = {}
    str_0 = "\x0c=xV4?#a$S#TGC8cX"
    track_0 = module_2.Track(dict_0, str_0)
    var_0 = track_0.__repr__()
    var_1 = var_0.__eq__(none_type_3)
    module_1.clear_queue(var_1)


def test_case_15():
    float_0 = 2623.0825
    track_0 = module_2.Track(float_0, float_0)
    var_0 = track_0.__repr__()
    var_1 = var_0.__repr__()
    var_2 = var_1.__repr__()
    var_3 = var_2.__repr__()
    module_1.clear_queue(var_3)


def test_case_16():
    none_type_0 = None
    player_state_0 = module_0.PlayerState(none_type_0, none_type_0)
    module_1.toggle_shuffle(player_state_0)
    str_0 = ""
    module_1.set_loop_mode(player_state_0, str_0)


def test_case_17():
    str_0 = "a"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.play_next(player_state_0, str_0)


def test_case_18():
    str_0 = "3\n@:z"
    none_type_0 = None
    player_state_0 = module_0.PlayerState(none_type_0, none_type_0)
    module_1.clear_queue(player_state_0)
    bytes_0 = b"\xdc\xb4\xf8\xd4\xa6\xf3R#\xbe"
    module_1.toggle_shuffle(bytes_0)
    module_1.play_next(player_state_0, str_0)


def test_case_19():
    bool_0 = False
    int_0 = -726
    module_1.add_to_queue(int_0, bool_0)


def test_case_20():
    bytes_0 = b""
    set_0 = {bytes_0, bytes_0}
    player_state_0 = module_0.PlayerState(set_0, set_0)
    none_type_0 = module_1.clear_queue(player_state_0)
    module_1.remove_from_queue(player_state_0, none_type_0)


def test_case_21():
    str_0 = "knG^"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.next_track(player_state_0)


def test_case_22():
    str_0 = "knG^"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.clear_queue(player_state_0)
    module_1.toggle_shuffle(player_state_0)
    module_1.next_track(player_state_0)


def test_case_23():
    float_0 = 853.0
    none_type_0 = None
    module_1.play_next(float_0, none_type_0)
    str_0 = "2.gfYlL"
    module_1.play_next(str_0, float_0)


def test_case_24():
    float_0 = 2623.0825
    track_0 = module_2.Track(float_0, float_0, float_0)
    list_0 = [track_0]
    bytes_0 = b"\xa0\x1f\t7i \xd2\xa9\x83c\x83\xb9"
    player_state_0 = module_0.PlayerState(list_0, bytes_0)
    module_1.play_next(player_state_0, track_0)


def test_case_25():
    none_type_0 = None
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, none_type_0)
    none_type_1 = module_1.next_track(player_state_0)
    float_0 = 1205.575014
    track_0 = module_2.Track(float_0, float_0)
    list_1 = [track_0, track_0]
    var_0 = track_0.__repr__()
    player_state_1 = module_0.PlayerState(list_1, none_type_1)
    str_0 = "o"
    none_type_2 = module_1.remove_from_queue(player_state_1, str_0)
    var_1 = track_0.__eq__(none_type_0)
    var_2 = var_1.__repr__()
    module_1.toggle_shuffle(var_2)
    player_state_2 = module_0.PlayerState(var_0, none_type_2)
    module_1.next_track(player_state_2)


def test_case_26():
    bytes_0 = b"G"
    set_0 = {bytes_0, bytes_0}
    player_state_0 = module_0.PlayerState(set_0, set_0)
    module_1.toggle_shuffle(player_state_0)


def test_case_27():
    bool_0 = True
    track_0 = module_2.Track(bool_0, bool_0)
    str_0 = "J}'\\r<A"
    tuple_0 = (track_0, str_0)
    player_state_0 = module_0.PlayerState(tuple_0, bool_0)
    module_1.clear_queue(player_state_0)
    var_0 = track_0.__eq__(track_0)
    module_1.set_loop_mode(var_0, var_0)


def test_case_28():
    bytes_0 = b"!p\xb3Uq\xa6;\x16\xa0"
    track_0 = module_2.Track(bytes_0, bytes_0, duration_seconds=bytes_0)
    list_0 = [track_0, track_0, track_0, track_0]
    player_state_0 = module_0.PlayerState(list_0, list_0)
    module_1.show_queue(player_state_0)


def test_case_29():
    list_0 = []
    none_type_0 = None
    str_0 = "[metrics] Error: Track path is empty."
    track_0 = module_2.Track(none_type_0, str_0)
    player_state_0 = module_0.PlayerState(list_0, track_0)
    bool_0 = True
    module_1.add_to_queue(player_state_0, bool_0)


def test_case_30():
    list_0 = []
    str_0 = "off"
    module_1.set_loop_mode(list_0, str_0)


def test_case_31():
    none_type_0 = None
    float_0 = 1205.575014
    track_0 = module_2.Track(float_0, float_0)
    list_0 = [track_0, track_0]
    var_0 = track_0.__eq__(none_type_0)
    var_1 = none_type_0.__repr__()
    player_state_0 = module_0.PlayerState(list_0, var_1)
    str_0 = "[=4"
    none_type_1 = module_1.remove_from_queue(player_state_0, str_0)
    var_2 = track_0.__eq__(none_type_0)
    none_type_2 = module_1.toggle_shuffle(var_2)
    module_1.set_loop_mode(none_type_2, var_1)
    player_state_1 = module_0.PlayerState(var_0, none_type_1)
    module_1.next_track(player_state_1)


def test_case_32():
    tuple_0 = ()
    none_type_0 = None
    module_1.remove_from_queue(none_type_0, tuple_0)


def test_case_33():
    none_type_0 = None
    player_state_0 = module_0.PlayerState(none_type_0, none_type_0)
    str_0 = ""
    module_1.set_loop_mode(player_state_0, str_0)
    module_1.toggle_shuffle(player_state_0)
    module_1.previous_track(player_state_0)


def test_case_34():
    str_0 = "knG^"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.add_to_queue(player_state_0, str_0)


def test_case_35():
    bytes_0 = b"\xdc\xb4\xf8\xd4\xa6\xf3R#\xbe"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.previous_track(player_state_0)


def test_case_36():
    str_0 = "knG^"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.toggle_shuffle(player_state_0)


def test_case_37():
    bytes_0 = b"\xbb"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.next_track(player_state_0)


def test_case_38():
    list_0 = []
    str_0 = "one"
    module_1.set_loop_mode(list_0, str_0)


def test_case_39():
    bytes_0 = b"\xdc\xb4\xf8\xd4\xa6\xf3R#\xbe"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.clear_queue(player_state_0)
    str_0 = "c|g$0~>D+/g2Wr'\nIJc"
    module_1.remove_from_queue(player_state_0, str_0)


def test_case_40():
    bytes_0 = b"G"
    set_0 = {bytes_0, bytes_0, bytes_0, bytes_0}
    none_type_0 = module_1.add_to_queue(set_0, set_0)
    str_0 = ""
    track_0 = module_2.Track(none_type_0, str_0, str_0)
    list_0 = [track_0, track_0, track_0]
    player_state_0 = module_0.PlayerState(list_0, bytes_0)
    module_1.add_to_queue(player_state_0, str_0)


def test_case_41():
    bytes_0 = b"\xdc\xb4\xf8\xd4\xa6\xf3R#\xbe"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    none_type_0 = module_1.toggle_shuffle(player_state_0)
    module_1.remove_from_queue(player_state_0, none_type_0)


def test_case_42():
    bytes_0 = b"G"
    set_0 = {bytes_0, bytes_0}
    player_state_0 = module_0.PlayerState(set_0, set_0)
    module_1.toggle_shuffle(player_state_0)
    module_1.toggle_shuffle(player_state_0)


def test_case_43():
    bytes_0 = b""
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.clear_queue(player_state_0)
    str_0 = ";wyf\x0b'/i/:7LR5Tgd:~"
    module_1.play_next(player_state_0, str_0)


def test_case_44():
    str_0 = ""
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.clear_queue(player_state_0)
    module_1.toggle_shuffle(player_state_0)


def test_case_45():
    bytes_0 = b"\xdc\xb4\xf8\xd4\xa6\xf3R#\xbe"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.toggle_shuffle(player_state_0)
    module_1.previous_track(player_state_0)


def test_case_46():
    bytes_0 = b"G"
    set_0 = {bytes_0, bytes_0, bytes_0, bytes_0}
    none_type_0 = module_1.add_to_queue(set_0, set_0)
    str_0 = "3"
    track_0 = module_2.Track(none_type_0, str_0, str_0)
    var_0 = track_0.__repr__()
    list_0 = [track_0, track_0]
    player_state_0 = module_0.PlayerState(list_0, var_0)
    module_1.add_to_queue(player_state_0, str_0)


def test_case_47():
    str_0 = "knG^"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.toggle_shuffle(player_state_0)
    module_1.next_track(player_state_0)


def test_case_48():
    str_0 = "knG^"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.toggle_shuffle(player_state_0)
    module_1.next_track(player_state_0)


def test_case_49():
    bytes_0 = b"\xdc\xb4\xf8\xd4\xa6\xf3R#\xbe"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.toggle_shuffle(player_state_0)
    module_1.next_track(player_state_0)


def test_case_50():
    bytes_0 = b"\t\xf3_"
    str_0 = ""
    track_0 = module_2.Track(str_0, str_0, str_0)
    var_0 = track_0.__repr__()
    track_1 = module_2.Track(var_0, bytes_0)
    list_0 = [track_1, track_1]
    player_state_0 = module_0.PlayerState(list_0, var_0)
    str_1 = 'XFs~"R~qJy|Dr`mm'
    module_1.play_next(player_state_0, str_1)
    track_2 = module_2.Track(bytes_0, str_0, bytes_0)
    str_2 = '\x0bjO6a&"'
    module_1.remove_from_queue(track_2, str_2)


def test_case_51():
    str_0 = "knG^"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.toggle_shuffle(player_state_0)
    module_1.next_track(player_state_0)


def test_case_52():
    bytes_0 = b"G"
    set_0 = {bytes_0, bytes_0}
    player_state_0 = module_0.PlayerState(set_0, set_0)
    module_1.clear_queue(player_state_0)
    str_0 = "6"
    module_1.remove_from_queue(player_state_0, str_0)


def test_case_53():
    str_0 = ""
    track_0 = module_2.Track(str_0, str_0, str_0)
    var_0 = track_0.__repr__()
    var_1 = var_0.__eq__(str_0)
    module_1.clear_queue(track_0)
    none_type_0 = module_1.toggle_shuffle(track_0)
    tuple_0 = (var_1,)
    module_1.play_next(tuple_0, none_type_0)