# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import music_player.time_utils as module_0


def test_case_0():
    none_type_0 = None
    str_0 = module_0.format_mm_ss(none_type_0)
    assert str_0 == "??:??"
    str_1 = ""
    module_0.parse_timecode(str_1)


def test_case_1():
    bool_0 = False
    str_0 = module_0.format_mm_ss(bool_0)
    assert str_0 == "00:00"


def test_case_2():
    bool_0 = False
    str_0 = module_0.format_mm_ss(bool_0)
    assert str_0 == "00:00"
    float_0 = module_0.parse_timecode(str_0)
    assert float_0 == pytest.approx(0.0, abs=0.01, rel=0.01)


def test_case_3():
    str_0 = "xVSd6\tE"
    module_0.parse_timecode(str_0)


def test_case_4():
    bool_0 = False
    str_0 = module_0.format_mm_ss(bool_0)
    assert str_0 == "00:00"
    float_0 = -2640.11
    str_1 = module_0.format_mm_ss(float_0)
    assert str_1 == "??:??"
    float_1 = module_0.parse_timecode(str_0)
    assert float_1 == pytest.approx(0.0, abs=0.01, rel=0.01)
    str_2 = "~>%"
    module_0.parse_timecode(str_2)


def test_case_5():
    bytes_0 = b"M"
    module_0.parse_timecode(bytes_0)
