# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import music_player.player_help as module_0


def test_case_0():
    str_0 = "R\\BYQ"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_1():
    str_0 = "W;"
    module_0.print_help(str_0)


def test_case_2():
    str_0 = "p|?"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_3():
    module_0.print_help()
    str_0 = "Rw"
    module_0.print_help(str_0)


def test_case_4():
    module_0.print_help()
    str_0 = "   h     list, /info, /[rogress, /bar"
    module_0.print_help(str_0)


def test_case_5():
    str_0 = "<"
    module_0.print_help(str_0)
    module_0.print_help()
    str_1 = "play"
    module_0.print_help(str_1)


def test_case_6():
    str_0 = "n"
    module_0.print_help(str_0)
    module_0.print_help()
    str_1 = ""
    module_0.print_help(str_1)


def test_case_7():
    str_0 = "n"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_8():
    str_0 = "R\\BYQ"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_9():
    str_0 = "\tBAR\t"
    module_0.print_help(str_0)
    module_0.print_help()
    str_1 = ""
    module_0.print_help(str_1)


def test_case_10():
    module_0.print_help()
    str_0 = "/volume"
    module_0.print_help(str_0)


def test_case_11():
    str_0 = "sO"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_12():
    str_0 = "n"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_13():
    module_0.print_help()
    str_0 = "stop"
    module_0.print_help(str_0)


def test_case_14():
    str_0 = "prog\tess"
    module_0.print_help()
    module_0.print_help(str_0)


def test_case_15():
    module_0.print_help()
    str_0 = "prev"
    module_0.print_help(str_0)


def test_case_16():
    str_0 = "n"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_17():
    str_0 = "NExt"
    module_0.print_help(str_0)
