# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
import pytest
import music_player.time_utils as module_0


# Test: checking that if no time is provided, the system shows '??:??' and handles blank inputs safely
def test_case_0():
    none_type_0 = None
    str_0 = module_0.format_mm_ss(none_type_0)
    assert str_0 == "??:??"
    str_1 = ""
    module_0.parse_timecode(str_1)


# Test: verifying that the time formatter can handle boolean values and shows them as zero
def test_case_1():
    bool_0 = False
    str_0 = module_0.format_mm_ss(bool_0)
    assert str_0 == "00:00"


# Test: checking that converting zero to text and then back to a number results in the correct value
def test_case_2():
    bool_0 = False
    str_0 = module_0.format_mm_ss(bool_0)
    assert str_0 == "00:00"
    float_0 = module_0.parse_timecode(str_0)
    assert float_0 == pytest.approx(0.0, abs=0.01, rel=0.01)


# Test: ensuring the system doesn't crash when trying to read random letters or tab spaces as a time
def test_case_3():
    str_0 = "xVSd6\tE"
    module_0.parse_timecode(str_0)


# Test: verifying that negative numbers show as an error and that random symbols don't break the system
def test_case_4():
    bool_0 = False
    str_0 = module_0.format_mm_ss(bool_0)
    assert str_0 == "00:00"
    float_0 = -2640.11
    str_1 = module_0.format_mm_ss(float_0)
    assert str_1 == "??:??"
    float_1 = module_0.parse_timecode(str_0)
    assert float_1 == pytest.approx(0.0, abs=0.01, rel=0.01)
    str_2 = "~>%"
    module_0.parse_timecode(str_2)


# Test: checking that the time parser can handle raw byte data without failing
def test_case_5():
    bytes_0 = b"M"
    module_0.parse_timecode(bytes_0)