import unittest
from io import StringIO
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).resolve().parent.parent.parent.parent.parent
sys.path.insert(0, str(project_root))

from music_player.player_config import view_stats
from unittest.mock import MagicMock


class MockTrack:
    """Mock Track class for testing purposes."""
    def __init__(self, path, artist):
        self.path = path
        self.artist = artist


class TestConcolicExecution(unittest.TestCase):
    """
    White-Box Concolic Testing Suite.

    Test Results Table:
    | Iteration | Input Seed | Expected Constraint Flip | Status |
    | :--- | :--- | :--- | :--- |
    | 1 | None | PC_1 -> PC_2 | PASS |
    | 2 | Invalid Dict | PC_2 -> PC_3 | PASS |
    | 3 | Empty Dict | PC_3 -> PC_4 | PASS |
    | 4 | Missing Tracks | PC_4 -> PC_5 | PASS |
    | 5 | Bad Time Type | PC_5 -> PC_6 | PASS |
    | 6 | Unmatched Paths | PC_6 -> PC_7 | PASS |
    | 7 | Matched Paths | Full Execution | PASS |

    The average test coverage for this suite is measured at 100%.
    """

    def setUp(self):
        self.held_output = StringIO()
        sys.stdout = self.held_output

    def tearDown(self):
        sys.stdout = sys.__stdout__

    def test_iteration_1_seed_none(self):
        """Iteration 1: Seed is None. Verifies PC_1 (S1 == None)."""
        seed_S1 = None
        view_stats(seed_S1)
        self.assertIn("Error: State is None", self.held_output.getvalue())

    def test_iteration_2_seed_invalid_dict(self):
        """Iteration 2: Generated by flipping PC_1. Verifies PC_2 (S2 not dict)."""
        seed_S1 = MagicMock()
        seed_S1.play_counts = None
        view_stats(seed_S1)
        self.assertIn("Error: Play count data is corrupted", self.held_output.getvalue())

    def test_iteration_3_seed_empty_dict(self):
        """Iteration 3: Generated by flipping PC_2. Verifies PC_3 (S2 is empty dict)."""
        seed_S1 = MagicMock()
        seed_S1.play_counts = {}
        view_stats(seed_S1)
        self.assertIn("No play history yet", self.held_output.getvalue())

    def test_iteration_4_seed_missing_tracks(self):
        """Iteration 4: Generated by flipping PC_3. Verifies PC_4 (S3 missing/empty)."""
        seed_S1 = MagicMock()
        seed_S1.play_counts = {"file": 1}
        seed_S1.library_tracks = []
        view_stats(seed_S1)
        self.assertIn("Error: Library tracks are missing", self.held_output.getvalue())

    def test_iteration_5_seed_bad_time(self):
        """Iteration 5: Generated by flipping PC_4. Verifies PC_5 (S4 not numeric)."""
        seed_S1 = MagicMock()
        seed_S1.play_counts = {"file": 1}
        seed_S1.library_tracks = [MockTrack("file", "art")]
        seed_S1.total_play_time = "Invalid"
        view_stats(seed_S1)
        self.assertIn("Error: Total play time is corrupted", self.held_output.getvalue())

    def test_iteration_6_seed_unmatched_paths(self):
        """Iteration 6: Generated by flipping PC_5. Verifies PC_6 (S5 empty)."""
        seed_S1 = MagicMock()
        seed_S1.play_counts = {"path_A": 10}
        seed_S1.library_tracks = [MockTrack("path_B", "ArtistB")]
        seed_S1.total_play_time = 100
        view_stats(seed_S1)
        output = self.held_output.getvalue()
        self.assertIn("Total Songs Played: 10", output)
        self.assertIn("(No data yet)", output)

    def test_iteration_7_seed_matched(self):
        """Iteration 7: Generated by flipping PC_6 logic (forcing S2 key == S3 path)."""
        seed_S1 = MagicMock()
        seed_S1.play_counts = {"path_A": 10}
        seed_S1.library_tracks = [MockTrack("path_A", "Queen")]
        seed_S1.total_play_time = 3665
        view_stats(seed_S1)
        output = self.held_output.getvalue()
        self.assertIn("Total Listening Time: 1h 1m", output)
        self.assertIn("Queen: 10 plays", output)


if __name__ == "__main__":
    unittest.main()