# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import music_player.playlist_model as module_0
import dataclasses as module_1
import music_player.library as module_2


def test_case_0():
    str_0 = ">x|q\tY"
    playlist_0 = module_0.Playlist(str_0)
    assert (
        f"{type(module_0.Playlist.num_tracks).__module__}.{type(module_0.Playlist.num_tracks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_seconds).__module__}.{type(module_0.Playlist.total_duration_seconds).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_mm_ss).__module__}.{type(module_0.Playlist.total_duration_mm_ss).__qualname__}"
        == "builtins.property"
    )
    str_1 = playlist_0.summary_line()
    assert str_1 == "  --  >x|q\tY                  0 tracks  00:00"


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "tb\x0cEm"
    playlist_0 = module_0.Playlist(str_0, str_0)
    assert (
        f"{type(module_0.Playlist.num_tracks).__module__}.{type(module_0.Playlist.num_tracks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_seconds).__module__}.{type(module_0.Playlist.total_duration_seconds).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_mm_ss).__module__}.{type(module_0.Playlist.total_duration_mm_ss).__qualname__}"
        == "builtins.property"
    )
    playlist_0.summary_line()


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = ""
    playlist_0 = module_0.Playlist(str_0)
    assert (
        f"{type(module_0.Playlist.num_tracks).__module__}.{type(module_0.Playlist.num_tracks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_seconds).__module__}.{type(module_0.Playlist.total_duration_seconds).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_mm_ss).__module__}.{type(module_0.Playlist.total_duration_mm_ss).__qualname__}"
        == "builtins.property"
    )
    var_0 = playlist_0.__repr__()
    var_1 = module_1.dataclass(order=var_0, frozen=var_0)
    playlist_0.summary_line(var_1)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "tb\x0cEm"
    playlist_0 = module_0.Playlist(str_0, str_0)
    assert (
        f"{type(module_0.Playlist.num_tracks).__module__}.{type(module_0.Playlist.num_tracks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_seconds).__module__}.{type(module_0.Playlist.total_duration_seconds).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_mm_ss).__module__}.{type(module_0.Playlist.total_duration_mm_ss).__qualname__}"
        == "builtins.property"
    )
    playlist_0.summary_line(active=str_0)


def test_case_4():
    none_type_0 = None
    var_0 = module_1.field(
        default_factory=none_type_0, compare=none_type_0, metadata=none_type_0
    )
    var_1 = var_0.__repr__()
    none_type_1 = None
    track_0 = module_2.Track(var_0, var_0, var_0, none_type_1)
    list_0 = [track_0, track_0, track_0]
    playlist_0 = module_0.Playlist(var_1, list_0)
    assert (
        f"{type(module_0.Playlist.num_tracks).__module__}.{type(module_0.Playlist.num_tracks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_seconds).__module__}.{type(module_0.Playlist.total_duration_seconds).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_mm_ss).__module__}.{type(module_0.Playlist.total_duration_mm_ss).__qualname__}"
        == "builtins.property"
    )
    bool_0 = True
    str_0 = playlist_0.summary_line(active=bool_0)
    assert (
        str_0
        == "* --  Field(name=None,type=None,default=<dataclasses._MISSING_TYPE object at 0x000001D02A61FCB0>,default_factory=None,init=True,repr=True,hash=None,compare=None,metadata=mappingproxy({}),kw_only=<dataclasses._MISSING_TYPE object at 0x000001D02A61FCB0>,_field_type=None)    3 tracks  00:00"
    )


@pytest.mark.xfail(strict=True)
def test_case_5():
    none_type_0 = None
    var_0 = module_1.field(
        default_factory=none_type_0, compare=none_type_0, metadata=none_type_0
    )
    str_0 = "m"
    track_0 = module_2.Track(str_0, str_0, str_0, var_0)
    list_0 = [track_0, track_0, track_0]
    playlist_0 = module_0.Playlist(str_0, list_0)
    assert (
        f"{type(module_0.Playlist.num_tracks).__module__}.{type(module_0.Playlist.num_tracks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_seconds).__module__}.{type(module_0.Playlist.total_duration_seconds).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_mm_ss).__module__}.{type(module_0.Playlist.total_duration_mm_ss).__qualname__}"
        == "builtins.property"
    )
    bool_0 = False
    playlist_0.summary_line(active=bool_0)
