# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import music_player.playlist_model as module_0
import music_player.library as module_1


def test_case_0():
    str_0 = "!X6"
    playlist_0 = module_0.Playlist(str_0, str_0)
    playlist_0.summary_line()


def test_case_1():
    str_0 = "!X6"
    none_type_0 = None
    playlist_0 = module_0.Playlist(none_type_0)
    playlist_0.summary_line(str_0)


def test_case_2():
    str_0 = ""
    playlist_0 = module_0.Playlist(str_0)
    playlist_0.summary_line()


def test_case_3():
    str_0 = "!X6"
    playlist_0 = module_0.Playlist(str_0, str_0)
    playlist_0.summary_line(active=str_0)


def test_case_4():
    str_0 = "!X6"
    bool_0 = False
    dict_0 = {str_0: bool_0, bool_0: bool_0}
    track_0 = module_1.Track(dict_0, bool_0)
    list_0 = [track_0, track_0, track_0, track_0]
    playlist_0 = module_0.Playlist(str_0, list_0)
    playlist_0.summary_line()


def test_case_5():
    str_0 = "j]W@p<"
    bool_0 = False
    dict_0 = {str_0: bool_0, str_0: str_0}
    track_0 = module_1.Track(str_0, dict_0, duration_seconds=bool_0)
    list_0 = [track_0, track_0, track_0, track_0, track_0]
    playlist_0 = module_0.Playlist(str_0, list_0)
    playlist_0.summary_line()
