# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import music_player.player_metrics as module_0
import re as module_1
import enum as module_2
import music_player.player_state as module_3


def test_case_0():
    none_type_0 = None
    module_0.load_data(none_type_0)


def test_case_1():
    list_0 = module_1.purge()
    module_0.show_liked_songs(list_0)


def test_case_2():
    int_0 = -2745
    module_0.show_liked_songs(int_0)


def test_case_3():
    var_0 = module_2._EnumDict()
    module_0.show_top_tracks(var_0)


def test_case_4():
    none_type_0 = None
    module_0.toggle_like(none_type_0)


def test_case_5():
    var_0 = module_1.RegexFlag.VERBOSE
    module_0.toggle_like(var_0)


def test_case_6():
    var_0 = module_1.purge()
    module_0.show_top_tracks(var_0)


def test_case_7():
    var_0 = module_1.purge()
    module_0.load_data(var_0)


def test_case_8():
    regex_flag_0 = module_1.RegexFlag.TEMPLATE
    module_0.show_top_tracks(regex_flag_0)


def test_case_9():
    regex_flag_0 = module_1.RegexFlag.DEBUG
    module_0.show_liked_songs(regex_flag_0)


def test_case_10():
    none_type_0 = None
    player_state_0 = module_3.PlayerState(none_type_0, none_type_0)
    module_0.toggle_like(player_state_0)


def test_case_11():
    str_0 = "uG"
    player_state_0 = module_3.PlayerState(str_0, str_0)
    module_0.toggle_like(player_state_0)


def test_case_12():
    none_type_0 = None
    player_state_0 = module_3.PlayerState(none_type_0, none_type_0)
    module_0.record_play(player_state_0)


def test_case_13():
    int_0 = -2024
    list_0 = [int_0, int_0, int_0]
    player_state_0 = module_3.PlayerState(list_0, int_0)
    module_0.record_play(player_state_0)
