# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import music_player.player_state as module_0
import music_player.player_ui as module_1
import music_player.library as module_2
import music_player.player_seek as module_3


def test_case_0():
    tuple_0 = ()
    player_state_0 = module_0.PlayerState(tuple_0, tuple_0)
    module_1.print_now_playing(player_state_0)


def test_case_1():
    str_0 = ",YHeu(lp]@1ons"
    module_1.print_progress(str_0)


def test_case_2():
    complex_0 = -2476 - 1613.2951013605839j
    track_0 = module_2.Track(complex_0, complex_0, complex_0)
    list_0 = [track_0]
    player_state_0 = module_0.PlayerState(list_0, list_0)
    module_1.print_now_playing(track_0)
    module_1.print_playlist_with_indicator(player_state_0)


def test_case_3():
    tuple_0 = ()
    player_state_0 = module_0.PlayerState(tuple_0, tuple_0)
    module_1.print_now_playing(player_state_0)
    module_1.print_progress(player_state_0)


def test_case_4():
    bool_0 = False
    module_1.print_progress_bar(bool_0)


def test_case_5():
    str_0 = "ax"
    track_0 = module_2.Track(str_0, str_0, str_0, str_0)
    list_0 = [track_0, track_0, track_0]
    list_1 = [list_0]
    player_state_0 = module_0.PlayerState(str_0, list_1)
    module_1.print_progress_bar(player_state_0)
    player_state_1 = module_0.PlayerState(list_0, list_1)
    module_1.print_playlist_with_indicator(player_state_1)


def test_case_6():
    tuple_0 = ()
    player_state_0 = module_0.PlayerState(tuple_0, tuple_0)
    none_type_0 = module_1.print_progress(player_state_0)
    none_type_1 = module_1.print_playlist_with_indicator(none_type_0)
    module_1.print_now_playing(none_type_1)
    module_1.print_now_playing(player_state_0)


def test_case_7():
    complex_0 = -2476 - 1613.2951013605839j
    track_0 = module_2.Track(complex_0, complex_0, complex_0)
    list_0 = [track_0]
    player_state_0 = module_0.PlayerState(list_0, list_0)
    module_1.print_playlist_with_indicator(player_state_0)


def test_case_8():
    complex_0 = -2476 - 1614.6127417137784j
    track_0 = module_2.Track(complex_0, complex_0, complex_0)
    list_0 = [track_0, track_0]
    player_state_0 = module_0.PlayerState(list_0, list_0)
    module_1.print_playlist_with_indicator(player_state_0)


def test_case_9():
    tuple_0 = ()
    player_state_0 = module_0.PlayerState(tuple_0, tuple_0)
    none_type_0 = module_1.print_playlist_with_indicator(player_state_0)
    module_1.print_now_playing(none_type_0)
    module_1.print_now_playing(player_state_0)
    module_1.print_progress(tuple_0)


def test_case_10():
    bool_0 = False
    tuple_0 = (bool_0, bool_0)
    tuple_1 = (bool_0, bool_0)
    none_type_0 = None
    module_1.print_progress(none_type_0)
    list_0 = [tuple_0, tuple_1, tuple_1]
    player_state_0 = module_0.PlayerState(tuple_1, bool_0)
    module_1.print_playlist_with_indicator(player_state_0)
    module_1.print_playlist_with_indicator(list_0)
    player_state_1 = module_0.PlayerState(list_0, bool_0)
    module_1.print_playlist_with_indicator(player_state_1)
    str_0 = "edxDfh'6|\x0cd6"
    set_0 = {str_0, str_0, str_0, str_0}
    none_type_1 = None
    module_1.print_now_playing(none_type_1)
    module_1.print_progress_bar(set_0)


def test_case_11():
    complex_0 = 933.7454 + 1433.4j
    tuple_0 = module_3.get_progress(complex_0)
    track_0 = module_2.Track(tuple_0, tuple_0, tuple_0)
    list_0 = [track_0]
    list_1 = []
    none_type_0 = None
    player_state_0 = module_0.PlayerState(list_1, none_type_0)
    module_1.print_playlist_with_indicator(player_state_0)
    bytes_0 = b"}\x06"
    player_state_1 = module_0.PlayerState(list_0, bytes_0)
    module_1.print_playlist_with_indicator(player_state_1)
    module_1.print_now_playing(player_state_1)


def test_case_12():
    complex_0 = -2476 - 1613.2951013605839j
    track_0 = module_2.Track(complex_0, complex_0, complex_0)
    list_0 = [track_0]
    player_state_0 = module_0.PlayerState(list_0, list_0)
    module_1.print_now_playing(player_state_0)


def test_case_13():
    complex_0 = 4259 + 3107.28j
    str_0 = "r\\9)\\"
    track_0 = module_2.Track(complex_0, str_0)
    var_0 = track_0.__repr__()
    var_1 = track_0.__repr__()
    module_1.print_now_playing(var_1)
    module_1.print_progress_bar(track_0)
    var_2 = str_0.__repr__()
    module_1.print_playlist_with_indicator(var_0)
    track_1 = module_2.Track(complex_0, var_2)
    list_0 = [track_0, track_1]
    player_state_0 = module_0.PlayerState(list_0, track_1)
    module_1.print_progress_bar(player_state_0)
    module_1.print_playlist_with_indicator(player_state_0)


def test_case_14():
    complex_0 = 933.7454 + 1433.4j
    tuple_0 = module_3.get_progress(complex_0)
    none_type_0 = None
    none_type_1 = None
    track_0 = module_2.Track(tuple_0, none_type_0, none_type_1)
    list_0 = [track_0]
    bytes_0 = b"\x8b\x84"
    player_state_0 = module_0.PlayerState(list_0, bytes_0)
    none_type_2 = module_1.print_playlist_with_indicator(player_state_0)
    module_1.print_now_playing(none_type_2)
