# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import music_player.player_audio as module_0
import builtins as module_1
import music_player.player_state as module_2


def test_case_0():
    none_type_0 = None
    module_0.toggle_mute(none_type_0)
    str_0 = "J\r/G"
    module_0.change_volume(none_type_0, str_0)
    list_0 = []
    module_0.change_volume(list_0, list_0)


def test_case_1():
    object_0 = module_1.object()
    complex_0 = -2562.74493 - 4702.034j
    list_0 = [object_0, complex_0]
    player_state_0 = module_2.PlayerState(list_0, complex_0)
    module_0.change_volume(player_state_0, player_state_0)


def test_case_2():
    object_0 = module_1.object()
    player_state_0 = module_2.PlayerState(object_0, object_0)
    module_0.toggle_mute(player_state_0)


def test_case_3():
    none_type_0 = None
    module_0.handle_mute_command(none_type_0, none_type_0)
    complex_0 = 2318.98 - 450.21758j
    player_state_0 = module_2.PlayerState(complex_0, none_type_0)
    float_0 = 74.946
    module_0.change_volume(player_state_0, float_0)


def test_case_4():
    list_0 = []
    player_state_0 = module_2.PlayerState(list_0, list_0)
    str_0 = ' "[\n'
    module_0.handle_mute_command(player_state_0, str_0)
    module_0.toggle_mute(player_state_0)


def test_case_5():
    bool_0 = True
    str_0 = "92~L"
    none_type_0 = module_0.change_volume(bool_0, str_0)
    list_0 = [none_type_0, bool_0]
    player_state_0 = module_2.PlayerState(list_0, bool_0)
    str_1 = ":mNF"
    module_0.handle_mute_command(player_state_0, str_1)


def test_case_6():
    bool_0 = True
    player_state_0 = module_2.PlayerState(bool_0, bool_0)
    module_0.change_volume(player_state_0, bool_0)


def test_case_7():
    int_0 = -1694
    module_0.change_volume(int_0, int_0)
    none_type_0 = None
    bool_0 = False
    module_0.toggle_mute(none_type_0)
    str_0 = "J\r/G"
    str_1 = "\t=L<"
    module_0.handle_mute_command(none_type_0, str_1)
    module_0.change_volume(none_type_0, str_0)
    list_0 = [none_type_0, bool_0]
    player_state_0 = module_2.PlayerState(list_0, bool_0)
    str_2 = "uA8B}lK1RV6![G"
    module_0.handle_mute_command(player_state_0, str_2)
    module_0.toggle_mute(player_state_0)


def test_case_8():
    none_type_0 = None
    str_0 = "|.WgN"
    module_0.handle_mute_command(none_type_0, none_type_0)
    bool_0 = True
    player_state_0 = module_2.PlayerState(bool_0, none_type_0)
    float_0 = 105.9
    module_0.change_volume(player_state_0, float_0)
    module_0.change_volume(bool_0, str_0)


def test_case_9():
    none_type_0 = None
    bool_0 = False
    module_0.toggle_mute(none_type_0)
    str_0 = "J\r/G"
    str_1 = "\t=L<"
    module_0.handle_mute_command(none_type_0, str_1)
    module_0.change_volume(none_type_0, str_0)
    list_0 = [none_type_0, bool_0]
    player_state_0 = module_2.PlayerState(list_0, bool_0)
    str_2 = "b#"
    module_0.handle_mute_command(player_state_0, str_2)
    module_0.toggle_mute(player_state_0)
