# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import music_player.user_data as module_0
import re as module_1
import music_player.player_state as module_2
import enum as module_3


def test_case_0():
    dict_0 = {}
    module_0.show_current_profile(dict_0)


def test_case_1():
    var_0 = module_1.RegexFlag.IGNORECASE
    module_0.view_rated(var_0)


def test_case_2():
    str_0 = 'v]GAP,#"nK'
    module_0.advanced_search(str_0, str_0)


def test_case_3():
    regex_flag_0 = module_1.RegexFlag.IGNORECASE
    module_0.load_profiles_index(regex_flag_0)


def test_case_4():
    var_0 = module_1.purge()
    module_0.advanced_search(var_0, var_0)


def test_case_5():
    none_type_0 = None
    module_0.create_profile(none_type_0, none_type_0)


def test_case_6():
    str_0 = 'v]GAP,#"nK'
    module_0.create_profile(str_0, str_0)


def test_case_7():
    regex_flag_0 = module_1.RegexFlag.IGNORECASE
    str_0 = "defilt"
    module_0.create_profile(regex_flag_0, str_0)
    module_0.load_profiles_index(regex_flag_0)


def test_case_8():
    regex_flag_0 = module_1.RegexFlag.DEBUG
    module_0.list_profiles(regex_flag_0)


def test_case_9():
    regex_flag_0 = module_1.RegexFlag.DEBUG
    module_0.view_rated(regex_flag_0)


def test_case_10():
    regex_flag_0 = module_1.RegexFlag.ASCII
    module_0.load_profiles_index(regex_flag_0)


def test_case_11():
    none_type_0 = None
    player_state_0 = module_2.PlayerState(none_type_0, none_type_0)
    module_0.rate_song(player_state_0, player_state_0)


def test_case_12():
    regex_flag_0 = module_1.RegexFlag.ASCII
    module_0.create_profile(regex_flag_0, regex_flag_0)


def test_case_13():
    regex_flag_0 = module_1.RegexFlag.ASCII
    module_0.load_profiles_index(regex_flag_0)


def test_case_14():
    enum_dict_0 = module_3._EnumDict()
    module_0.load_profiles_index(enum_dict_0)


def test_case_15():
    regex_flag_0 = module_1.RegexFlag.ASCII
    module_0.create_profile(regex_flag_0, regex_flag_0)


def test_case_16():
    none_type_0 = None
    player_state_0 = module_2.PlayerState(none_type_0, none_type_0)
    str_0 = 'Wv~s"4Uk6'
    module_0.advanced_search(player_state_0, str_0)


def test_case_17():
    regex_flag_0 = module_1.RegexFlag.IGNORECASE
    module_0.switch_profile(regex_flag_0, regex_flag_0)


def test_case_18():
    none_type_0 = None
    player_state_0 = module_2.PlayerState(none_type_0, none_type_0)
    str_0 = "KSEt"
    module_0.switch_profile(player_state_0, str_0)
    module_0.advanced_search(player_state_0, str_0)


def test_case_19():
    regex_flag_0 = module_1.RegexFlag.ASCII
    module_0.switch_profile(regex_flag_0, regex_flag_0)


def test_case_20():
    none_type_0 = None
    player_state_0 = module_2.PlayerState(none_type_0, none_type_0)
    module_0.create_profile(player_state_0, player_state_0)


def test_case_21():
    regex_flag_0 = module_1.RegexFlag.ASCII
    module_0.switch_profile(regex_flag_0, regex_flag_0)


def test_case_22():
    regex_flag_0 = module_1.RegexFlag.DOTALL
    module_0.load_profiles_index(regex_flag_0)


def test_case_23():
    regex_flag_0 = module_1.RegexFlag.ASCII
    none_type_0 = None
    list_0 = [regex_flag_0]
    player_state_0 = module_2.PlayerState(list_0, none_type_0)
    str_0 = ""
    module_0.advanced_search(player_state_0, str_0)


def test_case_24():
    none_type_0 = None
    list_0 = []
    player_state_0 = module_2.PlayerState(list_0, none_type_0)
    str_0 = "gxR^l_fA<`q_"
    none_type_1 = module_0.advanced_search(player_state_0, str_0)
    module_0.advanced_search(str_0, none_type_1)
    module_0.create_profile(str_0, player_state_0)
