# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
import music_player.player_help as module_0


def test_case_0():
    module_0.print_help()


def test_case_1():
    str_0 = "&}XBKN6"
    module_0.print_help(str_0)


def test_case_2():
    str_0 = "`N\x0c$"
    module_0.print_help(str_0)


def test_case_3():
    str_0 = "`N\x0c$"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_4():
    str_0 = "iPbno"
    module_0.print_help(str_0)


def test_case_5():
    str_0 = "F"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_6():
    str_0 = "Q"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_7():
    str_0 = "u"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_8():
    str_0 = "^G'dak((g8t$EK"
    module_0.print_help(str_0)


def test_case_9():
    str_0 = "GFf"
    module_0.print_help(str_0)


def test_case_10():
    str_0 = ""
    module_0.print_help(str_0)


def test_case_11():
    str_0 = "/profile.switnh"
    module_0.print_help()
    module_0.print_help(str_0)


def test_case_12():
    module_0.print_help()
    str_0 = 'yo"'
    module_0.print_help(str_0)


def test_case_13():
    str_0 = "';3"
    module_0.print_help(str_0)
    none_type_0 = None
    module_0.print_help(none_type_0)
    str_1 = "search"
    module_0.print_help(str_1)


def test_case_14():
    str_0 = " ht"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_15():
    module_0.print_help()
    str_0 = "schedule.cancel"
    module_0.print_help(str_0)


def test_case_16():
    str_0 = "bar"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_17():
    str_0 = "^G'dak((g8t$EK"
    none_type_0 = module_0.print_help(str_0)
    module_0.print_help(none_type_0)


def test_case_18():
    str_0 = "\\$vL#D]P{H,"
    module_0.print_help(str_0)
    str_1 = "pl.rename"
    module_0.print_help()
    module_0.print_help(str_1)


def test_case_19():
    str_0 = "m8"
    module_0.print_help(str_0)


def test_case_20():
    str_0 = "}%$}!"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_21():
    str_0 = "recnt"
    module_0.print_help(str_0)


def test_case_22():
    str_0 = "profilecDs"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_23():
    str_0 = "tag.add"
    module_0.print_help()
    module_0.print_help(str_0)


def test_case_24():
    str_0 = "q.lR\n%r)"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_25():
    module_0.print_help()
    str_0 = "6>m"
    module_0.print_help(str_0)


def test_case_26():
    module_0.print_help()
    str_0 = "tag.filter"
    module_0.print_help(str_0)


def test_case_27():
    str_0 = "pause"
    module_0.print_help(str_0)
    str_1 = "pl.rename"
    module_0.print_help()
    module_0.print_help(str_1)


def test_case_28():
    str_0 = "\\$vL#D]P{H,"
    module_0.print_help(str_0)
    str_1 = "pl.merge"
    module_0.print_help()
    module_0.print_help(str_1)


def test_case_29():
    str_0 = ":"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_30():
    str_0 = "pause"
    module_0.print_help(str_0)
    str_1 = "progress"
    module_0.print_help()
    module_0.print_help(str_1)


def test_case_31():
    module_0.print_help()
    str_0 = "p->l.show"
    module_0.print_help(str_0)


def test_case_32():
    str_0 = "Q'k"
    module_0.print_help(str_0)
    module_0.print_help()
    str_1 = "q.add"
    module_0.print_help(str_1)


def test_case_33():
    str_0 = "/next"
    module_0.print_help(str_0)
    str_1 = "progress"
    module_0.print_help()
    module_0.print_help(str_1)


def test_case_34():
    str_0 = "\\$vL#D]P{H,"
    module_0.print_help(str_0)
    str_1 = "unmute"
    module_0.print_help()
    module_0.print_help(str_1)


def test_case_35():
    str_0 = "artists"
    module_0.print_help(str_0)
    module_0.print_help()
    str_1 = "q.add"
    module_0.print_help(str_1)


def test_case_36():
    str_0 = "albums"
    module_0.print_help(str_0)
    str_1 = "progress"
    module_0.print_help()
    module_0.print_help(str_1)


def test_case_37():
    str_0 = "prfi`"
    module_0.print_help()
    module_0.print_help(str_0)


def test_case_38():
    str_0 = "/next"
    module_0.print_help(str_0)
    str_1 = "pl.list"
    module_0.print_help()
    module_0.print_help(str_1)


def test_case_39():
    str_0 = ":c6hHe{BEduS"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_40():
    str_0 = "artists"
    module_0.print_help(str_0)
    module_0.print_help()
    str_1 = "pl.move"
    module_0.print_help(str_1)


def test_case_41():
    str_0 = "shuffle"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_42():
    str_0 = "schedule"
    module_0.print_help(str_0)
    str_1 = "queue"
    module_0.print_help()
    module_0.print_help(str_1)


def test_case_43():
    str_0 = "list"
    module_0.print_help(str_0)
    str_1 = "unmute"
    module_0.print_help()
    module_0.print_help(str_1)


def test_case_44():
    str_0 = "Qc:n"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_45():
    str_0 = ")\\Huy"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_46():
    str_0 = "import"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_47():
    str_0 = "q.remove"
    module_0.print_help(str_0)


def test_case_48():
    str_0 = "\\$vL#D]P{H,"
    module_0.print_help(str_0)
    str_1 = "pl.play"
    module_0.print_help()
    module_0.print_help(str_1)


def test_case_49():
    str_0 = "prev"
    module_0.print_help(str_0)
    str_1 = "pl.merge"
    module_0.print_help()
    module_0.print_help(str_1)


def test_case_50():
    str_0 = "mute"
    module_0.print_help(str_0)


def test_case_51():
    str_0 = "albums"
    module_0.print_help(str_0)
    str_1 = "rw"
    module_0.print_help()
    module_0.print_help(str_1)


def test_case_52():
    str_0 = "pl.open"
    module_0.print_help(str_0)
    none_type_0 = None
    module_0.print_help(none_type_0)
    str_1 = "search"
    module_0.print_help(str_1)


def test_case_53():
    module_0.print_help()
    str_0 = "like"
    module_0.print_help(str_0)
    str_1 = "j?UmDp@7-(5 5Lk+IQa"
    module_0.print_help(str_1)


def test_case_54():
    str_0 = "pl.sort"
    module_0.print_help(str_0)
    str_1 = "progress"
    module_0.print_help()
    module_0.print_help(str_1)


def test_case_55():
    str_0 = "pl.\t}bxport"
    module_0.print_help(str_0)
    module_0.print_help()


def test_case_56():
    str_0 = "play"
    module_0.print_help(str_0)
    str_1 = "pl.play"
    module_0.print_help()
    module_0.print_help(str_1)
