# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import music_player.playlists_edit as module_0
import music_player.player_state as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "d\r"
    module_0.remove_track_from_playlist(str_0, str_0, str_0)


def test_case_1():
    str_0 = "@J'V0yuAthA\rQ_%"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    none_type_0 = None
    module_0.add_track_from_library(none_type_0, none_type_0, none_type_0)
    module_0.add_track_from_library(player_state_0, str_0, str_0)


def test_case_2():
    str_0 = "=9#,>/"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    module_0.add_track_from_library(player_state_0, str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "XUl>"
    none_type_0 = None
    module_0.remove_track_from_playlist(none_type_0, none_type_0, none_type_0)
    module_0.remove_track_from_playlist(str_0, str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "Sx\rreV|Hh"
    module_0.move_track_within_playlist(str_0, str_0, str_0, str_0)


def test_case_5():
    float_0 = -1795.2
    player_state_0 = module_1.PlayerState(float_0, float_0)
    str_0 = "n,xW"
    module_0.add_track_from_library(player_state_0, str_0, str_0)


def test_case_6():
    str_0 = ".m#"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    none_type_0 = module_0.remove_track_from_playlist(player_state_0, str_0, str_0)
    module_0.move_track_within_playlist(
        player_state_0, none_type_0, player_state_0, str_0
    )


def test_case_7():
    str_0 = "F3 YK4^e_hkm=."
    none_type_0 = None
    module_0.remove_track_from_playlist(str_0, str_0, none_type_0)


def test_case_8():
    float_0 = 864.03
    player_state_0 = module_1.PlayerState(float_0, float_0)
    str_0 = "n,xW"
    none_type_0 = module_0.remove_track_from_playlist(player_state_0, str_0, float_0)
    module_0.add_track_from_library(player_state_0, player_state_0, none_type_0)


def test_case_9():
    float_0 = 180.0
    player_state_0 = module_1.PlayerState(float_0, float_0)
    str_0 = "n,xW"
    none_type_0 = module_0.remove_track_from_playlist(player_state_0, str_0, float_0)
    module_0.move_track_within_playlist(player_state_0, str_0, str_0, str_0)
    module_0.move_track_within_playlist(
        none_type_0, player_state_0, player_state_0, str_0
    )


def test_case_10():
    str_0 = "XZ\x0cbjzS"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    module_0.move_track_within_playlist(player_state_0, str_0, str_0, str_0)


def test_case_11():
    str_0 = "[ce] Paysed"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    none_type_0 = module_0.move_track_within_playlist(
        player_state_0, str_0, str_0, str_0
    )
    module_0.move_track_within_playlist(player_state_0, str_0, none_type_0, str_0)


def test_case_12():
    str_0 = "XZ\x0cbjzS"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    module_0.remove_track_from_playlist(player_state_0, str_0, str_0)


def test_case_13():
    float_0 = 864.0
    player_state_0 = module_1.PlayerState(float_0, float_0)
    str_0 = "n,xW"
    none_type_0 = module_0.remove_track_from_playlist(player_state_0, str_0, float_0)
    module_0.add_track_from_library(player_state_0, player_state_0, none_type_0)


def test_case_14():
    float_0 = 180.0
    player_state_0 = module_1.PlayerState(float_0, float_0)
    str_0 = ""
    module_0.move_track_within_playlist(player_state_0, str_0, player_state_0, float_0)
    bool_0 = False
    str_1 = "n,xW"
    none_type_0 = module_0.remove_track_from_playlist(bool_0, bool_0, str_1)
    player_state_1 = module_1.PlayerState(none_type_0, str_1)
    str_2 = "J"
    module_0.add_track_from_library(player_state_1, player_state_1, str_2)


@pytest.mark.xfail(strict=True)
def test_case_15():
    str_0 = "mN:1M\x0c)U6<\x0c&ePY\x0b"
    float_0 = -0.0500104821602729
    none_type_0 = None
    module_0.move_track_within_playlist(str_0, str_0, str_0, none_type_0)
    module_0.remove_track_from_playlist(float_0, float_0, float_0)


@pytest.mark.xfail(strict=True)
def test_case_16():
    str_0 = "mN:1M\x0c)U6<\x0c&ePY\x0b"
    float_0 = -1.2705494208814505e-21
    none_type_0 = None
    module_0.move_track_within_playlist(str_0, str_0, str_0, none_type_0)
    module_0.remove_track_from_playlist(float_0, float_0, float_0)
