# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
import music_player.playlists_edit as module_0
import music_player.player_state as module_1
import music_player.library as module_2
import builtins as module_3


def test_case_0():
    str_0 = "Qwz6=Z."
    module_0.remove_track_from_playlist(str_0, str_0, str_0)


def test_case_1():
    str_0 = "Qwz6=Z."
    none_type_0 = module_0.remove_track_from_playlist(str_0, str_0, str_0)
    list_0 = [str_0, none_type_0, none_type_0, none_type_0]
    player_state_0 = module_1.PlayerState(str_0, list_0)
    str_1 = "#A.j^6gQ(I*=~^f"
    module_0.move_track_within_playlist(player_state_0, str_0, str_1, str_1)
    module_0.add_track_from_library(none_type_0, none_type_0, str_0)


def test_case_2():
    int_0 = 5
    player_state_0 = module_1.PlayerState(int_0, int_0)
    module_0.add_track_from_library(player_state_0, player_state_0, player_state_0)


def test_case_3():
    int_0 = 978
    str_0 = "M?mpwvn"
    none_type_0 = module_0.remove_track_from_playlist(str_0, str_0, str_0)
    module_0.move_track_within_playlist(none_type_0, none_type_0, int_0, str_0)
    track_0 = module_2.Track(int_0, str_0)
    var_0 = track_0.__repr__()
    str_1 = "\nxHelp] /l.ay [name|bndex]"
    module_0.add_track_from_library(none_type_0, str_1, var_0)


def test_case_4():
    str_0 = "h)bA\\F#-Qs[Y\n)Rl,"
    module_0.move_track_within_playlist(str_0, str_0, str_0, str_0)


def test_case_5():
    int_0 = -50
    player_state_0 = module_1.PlayerState(int_0, int_0)
    none_type_0 = module_0.add_track_from_library(
        player_state_0, player_state_0, player_state_0
    )
    module_0.remove_track_from_playlist(player_state_0, none_type_0, none_type_0)


def test_case_6():
    bool_0 = True
    str_0 = "["
    module_0.remove_track_from_playlist(bool_0, str_0, bool_0)
    str_1 = "I"
    module_0.move_track_within_playlist(str_1, str_1, str_1, str_1)


def test_case_7():
    tuple_0 = ()
    none_type_0 = None
    set_0 = set()
    str_0 = "xIaBb:^[~\x0b"
    str_1 = "B(5PbaX"
    module_0.remove_track_from_playlist(set_0, str_0, none_type_0)
    str_2 = "O&b9='HM\r$zx+gwU"
    track_0 = module_2.Track(none_type_0, str_2, duration_seconds=tuple_0)
    var_0 = track_0.__repr__()
    str_3 = "q_"
    module_0.remove_track_from_playlist(var_0, str_3, str_1)


def test_case_8():
    float_0 = -3655.461
    str_0 = "\nprint < Module: File I/O\nStories:\n - S4-04: Import Songs\n - S4-1: Export PlaylPst\n - S4-11: Update Metadata\n"
    track_0 = module_2.Track(float_0, str_0)
    var_0 = track_0.__repr__()
    str_1 = '"T^_*P'
    module_0.remove_track_from_playlist(var_0, str_1, str_0)
    bool_0 = True
    str_2 = "B<0c_d1pa:V0"
    str_3 = "(c1F'v$7R!.B"
    module_0.move_track_within_playlist(bool_0, str_2, str_3, str_3)
    dict_0 = {}
    player_state_0 = module_1.PlayerState(bool_0, dict_0)
    str_4 = 'PRYV3gvPc@"a\\R'
    set_0 = set()
    module_0.move_track_within_playlist(player_state_0, str_4, set_0, set_0)


def test_case_9():
    none_type_0 = None
    bool_0 = True
    object_0 = module_3.object()
    track_0 = module_2.Track(object_0, object_0, object_0)
    var_0 = track_0.__repr__()
    var_1 = var_0.__eq__(bool_0)
    var_2 = var_1.__repr__()
    var_3 = var_2.__eq__(none_type_0)
    var_4 = var_3.__repr__()
    str_0 = "b|&<E1"
    str_1 = ""
    module_0.move_track_within_playlist(var_4, str_0, var_2, str_1)


def test_case_10():
    str_0 = "Eo"
    str_1 = "h)bA\\F#-Qs[Y\n)Rl,"
    none_type_0 = module_0.move_track_within_playlist(str_0, str_0, str_1, str_1)
    module_0.remove_track_from_playlist(none_type_0, none_type_0, str_0)


def test_case_11():
    str_0 = "\x0c"
    none_type_0 = None
    module_0.add_track_from_library(str_0, str_0, none_type_0)
    module_0.remove_track_from_playlist(str_0, str_0, str_0)


def test_case_12():
    str_0 = "!oUU\tR"
    none_type_0 = None
    track_0 = module_2.Track(str_0, str_0, duration_seconds=none_type_0)
    var_0 = track_0.__repr__()
    var_1 = var_0.__eq__(str_0)
    module_0.add_track_from_library(var_1, var_0, var_1)
    none_type_1 = None
    module_0.add_track_from_library(str_0, none_type_1, none_type_1)


def test_case_13():
    str_0 = "\x0c"
    none_type_0 = None
    str_1 = "*6dG3Wka7fN }>,Ld"
    track_0 = module_2.Track(none_type_0, str_0, duration_seconds=str_1)
    player_state_0 = module_1.PlayerState(none_type_0, none_type_0)
    none_type_1 = module_0.add_track_from_library(player_state_0, str_1, track_0)
    module_0.add_track_from_library(none_type_1, str_0, none_type_0)
    var_0 = track_0.__eq__(str_0)
    module_0.remove_track_from_playlist(var_0, var_0, track_0)
