# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
import pytest
import music_player.playlists_edit as module_0
import music_player.player_state as module_1


@pytest.mark.xfail(strict=True)
# Test: checking that trying to remove a track using random strings as arguments triggers an error
def test_case_0():
    str_0 = "d\r"
    module_0.remove_track_from_playlist(str_0, str_0, str_0)


# Test: verifying that the system handles missing data (None) safely when adding songs from the library
def test_case_1():
    str_0 = "@J'V0yuAthA\rQ_%"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    none_type_0 = None
    module_0.add_track_from_library(none_type_0, none_type_0, none_type_0)
    module_0.add_track_from_library(player_state_0, str_0, str_0)


# Test: checking if adding a track to a playlist works when using unusual symbol strings
def test_case_2():
    str_0 = "=9#,>/"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    module_0.add_track_from_library(player_state_0, str_0, str_0)


@pytest.mark.xfail(strict=True)
# Test: ensuring the system identifies and rejects attempts to remove tracks when data is missing
def test_case_3():
    str_0 = "XUl>"
    none_type_0 = None
    module_0.remove_track_from_playlist(none_type_0, none_type_0, none_type_0)
    module_0.remove_track_from_playlist(str_0, str_0, str_0)


@pytest.mark.xfail(strict=True)
# Test: checking the robustness of the move track function against broken string inputs
def test_case_4():
    str_0 = "Sx\rreV|Hh"
    module_0.move_track_within_playlist(str_0, str_0, str_0, str_0)


# Test: verifying that the library addition logic stays stable when using negative numbers for the state
def test_case_5():
    float_0 = -1795.2
    player_state_0 = module_1.PlayerState(float_0, float_0)
    str_0 = "n,xW"
    module_0.add_track_from_library(player_state_0, str_0, str_0)


# Test: checking if moving a track within a playlist works correctly even after a removal attempt
def test_case_6():
    str_0 = ".m#"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    none_type_0 = module_0.remove_track_from_playlist(player_state_0, str_0, str_0)
    module_0.move_track_within_playlist(
        player_state_0, none_type_0, player_state_0, str_0
    )


# Test: verifying that removing a track doesn't crash if the track object itself is missing (None)
def test_case_7():
    str_0 = "F3 YK4^e_hkm=."
    none_type_0 = None
    module_0.remove_track_from_playlist(str_0, str_0, none_type_0)


# Test: checking the interaction between removing one track and adding another back to the state
def test_case_8():
    float_0 = 864.03
    player_state_0 = module_1.PlayerState(float_0, float_0)
    str_0 = "n,xW"
    none_type_0 = module_0.remove_track_from_playlist(player_state_0, str_0, float_0)
    module_0.add_track_from_library(player_state_0, player_state_0, none_type_0)


# Test: verifying that moving tracks still works even when the previous removal result was empty
def test_case_9():
    float_0 = 180.0
    player_state_0 = module_1.PlayerState(float_0, float_0)
    str_0 = "n,xW"
    none_type_0 = module_0.remove_track_from_playlist(player_state_0, str_0, float_0)
    module_0.move_track_within_playlist(player_state_0, str_0, str_0, str_0)
    module_0.move_track_within_playlist(
        none_type_0, player_state_0, player_state_0, str_0
    )


# Test: ensuring the track reordering function handles control characters like '\x0c' inside strings
def test_case_10():
    str_0 = "XZ\x0cbjzS"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    module_0.move_track_within_playlist(player_state_0, str_0, str_0, str_0)


# Test: checking the stability of the move function when given an empty result from a previous move
def test_case_11():
    str_0 = "[ce] Paysed"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    none_type_0 = module_0.move_track_within_playlist(
        player_state_0, str_0, str_0, str_0
    )
    module_0.move_track_within_playlist(player_state_0, str_0, none_type_0, str_0)


# Test: verifying the standard removal path when given a valid player state and track details
def test_case_12():
    str_0 = "XZ\x0cbjzS"
    player_state_0 = module_1.PlayerState(str_0, str_0)
    module_0.remove_track_from_playlist(player_state_0, str_0, str_0)


# Test: checking the library addition logic with high numeric values in the state
def test_case_13():
    float_0 = 864.0
    player_state_0 = module_1.PlayerState(float_0, float_0)
    str_0 = "n,xW"
    none_type_0 = module_0.remove_track_from_playlist(player_state_0, str_0, float_0)
    module_0.add_track_from_library(player_state_0, player_state_0, none_type_0)


# Test: verifying that the system correctly handles a mix of boolean, float, and string types in playlist edits
def test_case_14():
    float_0 = 180.0
    player_state_0 = module_1.PlayerState(float_0, float_0)
    str_0 = ""
    module_0.move_track_within_playlist(player_state_0, str_0, player_state_0, float_0)
    bool_0 = False
    str_1 = "n,xW"
    none_type_0 = module_0.remove_track_from_playlist(bool_0, bool_0, str_1)
    player_state_1 = module_1.PlayerState(none_type_0, str_1)
    str_2 = "J"
    module_0.add_track_from_library(player_state_1, player_state_1, str_2)


@pytest.mark.xfail(strict=True)
# Test: checking that complex strings and empty values together trigger an expected failure in move logic
def test_case_15():
    str_0 = "mN:1M\x0c)U6<\x0c&ePY\x0b"
    float_0 = -0.0500104821602729
    none_type_0 = None
    module_0.move_track_within_playlist(str_0, str_0, str_0, none_type_0)
    module_0.remove_track_from_playlist(float_0, float_0, float_0)


@pytest.mark.xfail(strict=True)
# Test: verifying error handling for very small scientific notation numbers in the playlist editor
def test_case_16():
    str_0 = "mN:1M\x0c)U6<\x0c&ePY\x0b"
    float_0 = -1.2705494208814505e-21
    none_type_0 = None
    module_0.move_track_within_playlist(str_0, str_0, str_0, none_type_0)
    module_0.remove_track_from_playlist(float_0, float_0, float_0)