import unittest
from unittest.mock import MagicMock, patch


# Replicating the class context for the Concolic suite
class AudioSystem:
    def __init__(self):
        self.volume = 0

    def set_volume(self, value: int) -> None:
        self.volume = value
        if globals().get('HAS_PYGAME'):
            vol_float = max(0.0, min(1.0, value / 100.0))
            if globals().get('pygame') and \
                    globals().get('pygame').mixer and \
                    globals().get('pygame').mixer.music:
                globals().get('pygame').mixer.music.set_volume(vol_float)


class TestConcolicGenerations(unittest.TestCase):
    '''
    -----------------------------------------------------------------------
    Test Results Table
    -----------------------------------------------------------------------
    Method              | Iteration | Constraint Flip | Status
    ------------------- | --------- | --------------- | ------
    test_iteration_1    | 1         | NOT S2          | PASS
    test_iteration_2    | 2         | NOT S3          | PASS
    test_iteration_3    | 3         | All Satisfied   | PASS
    -----------------------------------------------------------------------
    The average test coverage for this suite is measured at 100%.
    '''

    def setUp(self):
        self.audio = AudioSystem()
        # S1 (Concrete Seed Value)
        self.S1 = 50

    def test_iteration_1(self):
        """
        Iteration 1: Initial Concrete Seed.
        Vector: (S1=50, S2=False, S3=False) -> Target Path PC_3
        """
        S2_concrete = False
        S3_concrete = None  # Irrelevant due to S2 being False

        with patch.dict(globals(), {'HAS_PYGAME': S2_concrete}):
            self.audio.set_volume(self.S1)
            # Dynamic Check: Assert we stayed in the shallow path
            self.assertEqual(self.audio.volume, 50)

    def test_iteration_2(self):
        """
        Iteration 2: Generated by flipping constraint (NOT S2) -> S2.
        Vector: (S1=50, S2=True, S3=False) -> Target Path PC_2
        """
        S2_concrete = True
        # We purposely break S3 to explore the False branch of the inner decision
        mock_pygame = MagicMock()
        mock_pygame.mixer = None  # S3 becomes False

        with patch.dict(globals(), {'HAS_PYGAME': S2_concrete, 'pygame': mock_pygame}):
            self.audio.set_volume(self.S1)
            # Dynamic Check: Code should execute without error but perform no music action
            self.assertEqual(self.audio.volume, 50)

    def test_iteration_3(self):
        """
        Iteration 3: Generated by flipping constraint (NOT S3) -> S3.
        Vector: (S1=50, S2=True, S3=True) -> Target Path PC_1
        """
        S2_concrete = True
        # We reconstruct S3 to be Valid
        mock_pygame = MagicMock()
        # Ensure the chain exists
        mock_music = mock_pygame.mixer.music

        with patch.dict(globals(), {'HAS_PYGAME': S2_concrete, 'pygame': mock_pygame}):
            self.audio.set_volume(self.S1)

            # Dynamic Check: Full path traversal
            expected_float = 0.5
            mock_music.set_volume.assert_called_once_with(expected_float)


if __name__ == '__main__':
    unittest.main()