# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import music_player.player_state as module_0
import music_player.playlists_advanced as module_1


def test_case_0():
    none_type_0 = None
    player_state_0 = module_0.PlayerState(none_type_0, none_type_0)
    module_1.copy_playlist(player_state_0, none_type_0, player_state_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "e"
    str_1 = "i"
    none_type_0 = None
    player_state_0 = module_0.PlayerState(none_type_0, none_type_0)
    module_1.merge_playlists(player_state_0, str_0, str_1)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "IV8"
    str_1 = "i"
    none_type_0 = None
    player_state_0 = module_0.PlayerState(none_type_0, none_type_0)
    module_1.merge_playlists(player_state_0, str_0, str_1)


def test_case_3():
    str_0 = "i"
    int_0 = 1990
    none_type_0 = None
    player_state_0 = module_0.PlayerState(none_type_0, int_0)
    list_0 = []
    module_1.merge_playlists(player_state_0, str_0, list_0)


def test_case_4():
    str_0 = ""
    str_1 = "i"
    none_type_0 = None
    player_state_0 = module_0.PlayerState(none_type_0, none_type_0)
    module_1.merge_playlists(player_state_0, str_0, str_1)


@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = "e"
    str_1 = "*i"
    none_type_0 = None
    player_state_0 = module_0.PlayerState(none_type_0, none_type_0)
    module_1.merge_playlists(player_state_0, str_0, str_1)
