# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import music_player.playlists_advanced as module_0
import music_player.player_state as module_1
import music_player.playlist_model as module_2


def test_case_0():
    none_type_0 = None
    module_0.merge_playlists(none_type_0, none_type_0, none_type_0)


def test_case_1():
    none_type_0 = None
    player_state_0 = module_1.PlayerState(none_type_0, none_type_0)
    str_0 = ""
    module_0.copy_playlist(player_state_0, str_0, str_0)


def test_case_2():
    none_type_0 = None
    player_state_0 = module_1.PlayerState(none_type_0, none_type_0)
    str_0 = "S[zQ+"
    none_type_1 = module_0.merge_playlists(player_state_0, str_0, str_0)
    module_0.copy_playlist(none_type_1, none_type_0, none_type_0)


def test_case_3():
    bytes_0 = b"\x8f\x9a\xe0.\xe9\xd8\x06\xce?\xd3\xc9Ld\xb2\xcd\xe2\xf3#\xcc"
    player_state_0 = module_1.PlayerState(bytes_0, bytes_0)
    module_0.merge_playlists(player_state_0, bytes_0, bytes_0, bytes_0)


def test_case_4():
    none_type_0 = None
    none_type_1 = module_0.merge_playlists(none_type_0, none_type_0, none_type_0)
    none_type_2 = module_0.merge_playlists(none_type_0, none_type_0, none_type_0)
    str_0 = ",0+\x0b\\"
    str_1 = ". |rrr:bvxld PAaUst/"
    module_0.merge_playlists(none_type_1, str_1, none_type_1, none_type_1)
    module_0.merge_playlists(none_type_2, str_0, str_0, str_0)


def test_case_5():
    none_type_0 = None
    str_0 = "HB{Hj?|"
    module_0.merge_playlists(none_type_0, str_0, str_0)


def test_case_6():
    bytes_0 = b"\x1e=!\xbba\n\x82R\xf7,\xde\xfc"
    playlist_0 = module_2.Playlist(bytes_0)
    var_0 = playlist_0.__repr__()
    str_0 = "help"
    module_0.copy_playlist(var_0, str_0, str_0)


def test_case_7():
    bytes_0 = b"\x8f\x9a\xe0.\xe9\xd8\x7f\xce?\xd3\xc9Ld\xb2\xcd\xe2\xf3#\xcc"
    none_type_0 = None
    str_0 = ""
    module_0.merge_playlists(none_type_0, bytes_0, str_0, none_type_0)
    player_state_0 = module_1.PlayerState(bytes_0, bytes_0)
    module_0.merge_playlists(player_state_0, bytes_0, bytes_0, bytes_0)


def test_case_8():
    none_type_0 = None
    player_state_0 = module_1.PlayerState(none_type_0, none_type_0)
    str_0 = "6\\l"
    module_0.merge_playlists(player_state_0, str_0, str_0)


def test_case_9():
    none_type_0 = None
    player_state_0 = module_1.PlayerState(none_type_0, none_type_0)
    str_0 = ""
    module_0.copy_playlist(player_state_0, none_type_0, str_0)
    module_0.merge_playlists(none_type_0, str_0, none_type_0)


def test_case_10():
    none_type_0 = None
    none_type_1 = module_0.merge_playlists(none_type_0, none_type_0, none_type_0)
    str_0 = "YX!"
    player_state_0 = module_1.PlayerState(none_type_0, none_type_0)
    bytes_0 = b"\xf5\xd7|T(A\x06\xe8"
    module_0.copy_playlist(player_state_0, bytes_0, str_0)
    module_0.merge_playlists(player_state_0, str_0, str_0)
    str_1 = "q+E/,C0lfGv4xG$W)_oF"
    module_0.merge_playlists(none_type_0, str_1, none_type_1)
