# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import music_player.player_core as module_0
import music_player.player_state as module_1


def test_case_0():
    bool_0 = True
    list_0 = [bool_0, bool_0]
    none_type_0 = None
    module_0.set_sleep_timer(none_type_0, none_type_0)
    module_0.update_playback(list_0, bool_0)


def test_case_1():
    bool_0 = True
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    none_type_0 = None
    module_0.set_playback_speed(none_type_0, none_type_0)
    module_0.stop(player_state_0)


def test_case_2():
    float_0 = 1.7381569080945711
    module_0.set_playback_speed(float_0, float_0)


def test_case_3():
    bool_0 = False
    module_0.set_playback_speed(bool_0, bool_0)


def test_case_4():
    bool_0 = True
    module_0.update_playback(bool_0, bool_0)


def test_case_5():
    bool_0 = True
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    module_0.set_sleep_timer(player_state_0, bool_0)


def test_case_6():
    bool_0 = False
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    module_0.set_sleep_timer(player_state_0, bool_0)


def test_case_7():
    bool_0 = False
    bool_1 = False
    module_0.update_playback(bool_0, bool_1)


def test_case_8():
    list_0 = []
    module_0.set_playback_speed(list_0, list_0)


def test_case_9():
    float_0 = 2962.8935
    module_0.set_playback_speed(float_0, float_0)
    bool_0 = True
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    module_0.set_sleep_timer(player_state_0, bool_0)
    module_0.update_playback(player_state_0, player_state_0)


def test_case_10():
    none_type_0 = None
    player_state_0 = module_1.PlayerState(none_type_0, none_type_0)
    module_0.play(player_state_0)


def test_case_11():
    bool_0 = True
    int_0 = 1440
    module_0.set_sleep_timer(bool_0, int_0)


def test_case_12():
    bool_0 = True
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    module_0.pause(player_state_0)


def test_case_13():
    bool_0 = True
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    module_0.stop(player_state_0)


def test_case_14():
    bool_0 = True
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    module_0.update_playback(player_state_0, bool_0)


def test_case_15():
    bool_0 = True
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    module_0.set_playback_speed(player_state_0, bool_0)


def test_case_16():
    bool_0 = False
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    none_type_0 = module_0.pause(player_state_0)
    module_0.stop(player_state_0)
    int_0 = 2999
    module_0.set_sleep_timer(player_state_0, none_type_0)
    module_0.set_sleep_timer(player_state_0, int_0)


def test_case_17():
    bool_0 = True
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    module_0.set_sleep_timer(player_state_0, bool_0)
    module_0.set_sleep_timer(player_state_0, bool_0)


def test_case_18():
    bool_0 = True
    none_type_0 = None
    player_state_0 = module_1.PlayerState(bool_0, none_type_0)
    module_0.set_sleep_timer(player_state_0, bool_0)


def test_case_19():
    bool_0 = True
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    module_0.set_sleep_timer(player_state_0, bool_0)
    module_0.update_playback(player_state_0, player_state_0)


def test_case_20():
    bool_0 = True
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    int_0 = 1430
    module_0.set_sleep_timer(player_state_0, int_0)


def test_case_21():
    bool_0 = True
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    int_0 = 1660
    module_0.set_sleep_timer(player_state_0, int_0)


def test_case_22():
    bool_0 = True
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    module_0.set_sleep_timer(player_state_0, bool_0)
    bool_1 = False
    module_0.set_sleep_timer(player_state_0, bool_1)


def test_case_23():
    bool_0 = True
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    int_0 = 689
    module_0.set_sleep_timer(player_state_0, int_0)
    module_0.set_sleep_timer(player_state_0, int_0)
    module_0.update_playback(player_state_0, int_0)


def test_case_24():
    bool_0 = True
    list_0 = [bool_0, bool_0, bool_0, bool_0]
    player_state_0 = module_1.PlayerState(list_0, bool_0)
    module_0.play(player_state_0)


def test_case_25():
    bool_0 = False
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    float_0 = 2.0
    module_0.set_playback_speed(player_state_0, float_0)


def test_case_26():
    bool_0 = True
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    float_0 = 2.0
    module_0.set_sleep_timer(player_state_0, bool_0)
    module_0.set_playback_speed(player_state_0, float_0)
    int_0 = 1440
    module_0.set_sleep_timer(player_state_0, int_0)


def test_case_27():
    bool_0 = False
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    float_0 = 0.5
    module_0.set_sleep_timer(player_state_0, float_0)


def test_case_28():
    bool_0 = False
    player_state_0 = module_1.PlayerState(bool_0, bool_0)
    float_0 = 9e-09
    module_0.set_sleep_timer(player_state_0, float_0)
