# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import music_player.player_state as module_0
import music_player.player_core as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\x1e!\xf6\x10\x1c\x85\x93\x0e\xbcYw\xc2!I"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.play(player_state_0)


def test_case_1():
    none_type_0 = None
    player_state_0 = module_0.PlayerState(none_type_0, none_type_0)
    module_1.play(player_state_0)


def test_case_2():
    bool_0 = True
    player_state_0 = module_0.PlayerState(bool_0, bool_0)
    module_1.pause(player_state_0)


def test_case_3():
    str_0 = ",g fmI\x0b 3r\n+z"
    int_0 = -4293
    module_1.update_playback(str_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    int_0 = 100
    set_0 = {int_0, int_0, int_0, int_0}
    module_1.update_playback(set_0, int_0)


def test_case_5():
    none_type_0 = None
    player_state_0 = module_0.PlayerState(none_type_0, none_type_0)
    module_1.stop(player_state_0)


def test_case_6():
    bool_0 = True
    player_state_0 = module_0.PlayerState(bool_0, bool_0)
    module_1.update_playback(player_state_0, bool_0)
