# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import enum as module_0
import music_player.playlists_basic as module_1
import re as module_2
import music_player.player_state as module_3


def test_case_0():
    var_0 = module_0._EnumDict()
    module_1.show_current_playlist(var_0)


def test_case_1():
    var_0 = module_2.purge()
    module_1.show_current_playlist(var_0)


def test_case_2():
    var_0 = module_2.purge()
    module_1.open_playlist(var_0, var_0)


def test_case_3():
    none_type_0 = None
    module_1.rename_playlist(none_type_0, none_type_0, none_type_0)


def test_case_4():
    enum_dict_0 = module_0._EnumDict()
    module_1.close_playlist(enum_dict_0)


def test_case_5():
    none_type_0 = None
    module_1.sort_playlist(none_type_0, none_type_0, none_type_0)


def test_case_6():
    bytes_0 = b"\xf6"
    player_state_0 = module_3.PlayerState(bytes_0, bytes_0)
    module_1.create_playlist(player_state_0, bytes_0)


def test_case_7():
    none_type_0 = None
    module_1.play_playlist(none_type_0, none_type_0)


def test_case_8():
    str_0 = "]U7\t%3(Ig"
    module_1.sort_playlist(str_0, str_0, str_0)


def test_case_9():
    var_0 = module_2.purge()
    module_1.list_playlists(var_0)


def test_case_10():
    var_0 = module_2.purge()
    str_0 = "fwZ{"
    module_1.open_playlist(var_0, str_0)


def test_case_11():
    none_type_0 = None
    module_1.create_playlist(none_type_0, none_type_0)


def test_case_12():
    enum_dict_0 = module_0._EnumDict()
    module_1.sort_playlist(enum_dict_0, enum_dict_0, enum_dict_0)


def test_case_13():
    none_type_0 = None
    str_0 = "bgFx;RN["
    module_1.rename_playlist(none_type_0, none_type_0, str_0)


def test_case_14():
    none_type_0 = None
    module_1.delete_playlist(none_type_0, none_type_0)


def test_case_15():
    bytes_0 = b"\x9e\xe7e\x9c'U\x9e\x95\x04\x170"
    module_1.sort_playlist(bytes_0, bytes_0, bytes_0)
    str_0 = "Oid"
    module_1.rename_playlist(str_0, str_0, str_0)


def test_case_16():
    bytes_0 = b"\x04"
    player_state_0 = module_3.PlayerState(bytes_0, bytes_0)
    module_1.list_playlists(player_state_0)


def test_case_17():
    bytes_0 = b"\x04"
    player_state_0 = module_3.PlayerState(bytes_0, bytes_0)
    module_1.open_playlist(player_state_0, player_state_0)


def test_case_18():
    var_0 = module_2.purge()
    str_0 = ""
    module_1.open_playlist(var_0, str_0)


def test_case_19():
    bytes_0 = b"\x04"
    player_state_0 = module_3.PlayerState(bytes_0, bytes_0)
    module_1.play_active_playlist(player_state_0)


def test_case_20():
    bytes_0 = b"8\x9bh\x1fta8(\xe9b}\xf8\xf2tb"
    player_state_0 = module_3.PlayerState(bytes_0, bytes_0)
    module_1.delete_playlist(player_state_0, bytes_0)


def test_case_21():
    bytes_0 = b"\x04"
    player_state_0 = module_3.PlayerState(bytes_0, bytes_0)
    module_1.close_playlist(player_state_0)


def test_case_22():
    none_type_0 = None
    player_state_0 = module_3.PlayerState(none_type_0, none_type_0)
    str_0 = "rv"
    module_1.create_playlist(player_state_0, str_0)
    module_1.open_playlist(player_state_0, str_0)


def test_case_23():
    none_type_0 = None
    module_1.close_playlist(none_type_0)
    player_state_0 = module_3.PlayerState(none_type_0, none_type_0)
    str_0 = "eg-Q\x0b.$@]<DEz\nO\\"
    str_1 = "rv"
    module_1.create_playlist(player_state_0, str_1)
    module_1.open_playlist(player_state_0, str_0)


def test_case_24():
    none_type_0 = None
    str_0 = "~by?!Ff%PoplQXPgMpAT"
    module_1.sort_playlist(str_0, str_0, none_type_0)


def test_case_25():
    bytes_0 = b"\x04"
    player_state_0 = module_3.PlayerState(bytes_0, bytes_0)
    module_1.show_current_playlist(player_state_0)


def test_case_26():
    bytes_0 = b"8\x9bh\x1fta8(\xe9b}\xf8\xf2tb"
    player_state_0 = module_3.PlayerState(bytes_0, bytes_0)
    str_0 = ""
    module_1.rename_playlist(player_state_0, str_0, str_0)


def test_case_27():
    bytes_0 = b"\xf6"
    player_state_0 = module_3.PlayerState(bytes_0, bytes_0)
    str_0 = ""
    module_1.sort_playlist(player_state_0, str_0, str_0)


def test_case_28():
    bytes_0 = b"\xf6"
    player_state_0 = module_3.PlayerState(bytes_0, bytes_0)
    module_1.create_playlist(player_state_0, bytes_0)
    module_1.play_active_playlist(player_state_0)


def test_case_29():
    bytes_0 = b"8\x9bh\x1ftA8(\xe9B}\xf8\xf2tB"
    player_state_0 = module_3.PlayerState(bytes_0, bytes_0)
    module_1.create_playlist(player_state_0, bytes_0)
    module_1.show_current_playlist(player_state_0)


def test_case_30():
    bytes_0 = b"\x8f\x80&Gn\x8b\x9d\xdbM\xed\x1e\xb8"
    player_state_0 = module_3.PlayerState(bytes_0, bytes_0)
    str_0 = ""
    none_type_0 = module_1.open_playlist(player_state_0, str_0)
    str_1 = "p3)s"
    module_1.rename_playlist(none_type_0, str_1, none_type_0)


def test_case_31():
    bytes_0 = b"8\x9bh\x1ftA8(9B}\xf8\xd5\xbeB\x0e"
    player_state_0 = module_3.PlayerState(bytes_0, bytes_0)
    module_1.create_playlist(player_state_0, bytes_0)
    module_1.list_playlists(player_state_0)


def test_case_32():
    none_type_0 = None
    player_state_0 = module_3.PlayerState(none_type_0, none_type_0)
    str_0 = "rv"
    module_1.create_playlist(player_state_0, str_0)
    module_1.create_playlist(player_state_0, str_0)


def test_case_33():
    bytes_0 = b"8\x9bh\x1ftA8(\xe9B}\xf8\xf2tB"
    player_state_0 = module_3.PlayerState(bytes_0, bytes_0)
    module_1.create_playlist(player_state_0, bytes_0)
    module_1.create_playlist(player_state_0, bytes_0)
    module_1.list_playlists(player_state_0)


def test_case_34():
    bytes_0 = b"8\x9bh\x1ftA8(9B}\xf8\xd5\xbeB\x0e "
    player_state_0 = module_3.PlayerState(bytes_0, bytes_0)
    module_1.create_playlist(player_state_0, bytes_0)
    module_1.close_playlist(player_state_0)
    module_1.list_playlists(player_state_0)


def test_case_35():
    str_0 = "\t"
    module_1.sort_playlist(str_0, str_0, str_0)
