# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import music_player.player_state as module_0
import music_player.playlists_basic as module_1


def test_case_0():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    module_1.list_playlists(player_state_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"\x88B\x1c\xbby9\xe0V\xd5K\xedI\x01"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.rename_playlist(player_state_0, player_state_0, player_state_0)


def test_case_2():
    int_0 = -678
    module_1.close_playlist(int_0)


def test_case_3():
    bytes_0 = b""
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.create_playlist(player_state_0, bytes_0)


def test_case_4():
    bytes_0 = b""
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.delete_playlist(player_state_0, bytes_0)


def test_case_5():
    bytes_0 = b"@"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.play_playlist(player_state_0, bytes_0)


def test_case_6():
    bytes_0 = b"\x99\x8aJB;\x85\x11\xcb\xaa\xafP\x13\xf76\xca\xb0"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.delete_playlist(player_state_0, bytes_0)


def test_case_7():
    bytes_0 = b"\x93;u*jkL\xe1\x1c\x12b\x9dT?\xf5yG\x1b"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.show_current_playlist(player_state_0)


@pytest.mark.xfail(strict=True)
def test_case_8():
    bytes_0 = b"9\x8aB;\x85\x11\xcb\xaa\xafP\x13\xf76\xca"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.create_playlist(player_state_0, player_state_0)


def test_case_9():
    bytes_0 = b"\x93;u*jkL\xe1\x1c\x12b\x9dT?\xf5yG\x1b"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    none_type_0 = module_1.create_playlist(player_state_0, bytes_0)
    assert len(player_state_0.playlists) == 1
    assert player_state_0.active_playlist_index == 0


def test_case_10():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    module_1.close_playlist(player_state_0)


def test_case_11():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    str_0 = "\x0b%}>=}"
    module_1.open_playlist(player_state_0, str_0)


def test_case_12():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    module_1.play_active_playlist(player_state_0)


def test_case_13():
    bytes_0 = b"@"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    str_0 = "8<e"
    module_1.delete_playlist(player_state_0, str_0)
    none_type_0 = None
    module_1.rename_playlist(player_state_0, player_state_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_14():
    bytes_0 = b"\xcf\x99\xb13\x98<\xfc\xe3"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.rename_playlist(player_state_0, player_state_0, bytes_0)


def test_case_15():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    str_0 = "WA6882)ka$$-Vu"
    none_type_0 = module_1.create_playlist(player_state_0, str_0)
    assert len(player_state_0.playlists) == 1
    assert player_state_0.active_playlist_index == 0
    module_1.create_playlist(player_state_0, str_0)
    module_1.list_playlists(player_state_0)


def test_case_16():
    bytes_0 = b"\x90\xd0\xf3\xb2\xeb\x14f\x91W\x83\xc2\x87\x98.\xf2m\x9c\xe1"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    none_type_0 = module_1.create_playlist(player_state_0, bytes_0)
    assert len(player_state_0.playlists) == 1
    assert player_state_0.active_playlist_index == 0
    str_0 = "*N$alK.d"
    none_type_1 = module_1.create_playlist(player_state_0, str_0)
    assert len(player_state_0.playlists) == 2
    module_1.list_playlists(player_state_0)


def test_case_17():
    bytes_0 = b"|\xea\xaa\xa1#-\xad@!\x1c\xf9"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    str_0 = "8j[T\nt\x0cC=bp^0"
    module_1.rename_playlist(player_state_0, bytes_0, str_0)
    module_1.show_current_playlist(player_state_0)


def test_case_18():
    bytes_0 = b"\x93;u*jkL\xe1\x1c\x12b\x9dT?\xf5yG\x1b"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    none_type_0 = module_1.create_playlist(player_state_0, bytes_0)
    assert len(player_state_0.playlists) == 1
    assert player_state_0.active_playlist_index == 0
    module_1.play_active_playlist(player_state_0)


def test_case_19():
    bytes_0 = b"\x93;u*jkL\xe1\x1c\x12b\x9dT?\xf5yG\x1b"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    none_type_0 = module_1.create_playlist(player_state_0, bytes_0)
    assert len(player_state_0.playlists) == 1
    assert player_state_0.active_playlist_index == 0
    module_1.show_current_playlist(player_state_0)


def test_case_20():
    bytes_0 = b"\x93;u*jkL\xe1\x1c\x12b\x9dT?\xf5yG\x1b"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    none_type_0 = module_1.create_playlist(player_state_0, bytes_0)
    assert len(player_state_0.playlists) == 1
    assert player_state_0.active_playlist_index == 0
    module_1.list_playlists(player_state_0)


def test_case_21():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    str_0 = "\x0b%}>=}"
    module_1.open_playlist(player_state_0, str_0)
    str_1 = "HXERS7"
    none_type_0 = module_1.create_playlist(player_state_0, str_1)
    assert len(player_state_0.playlists) == 1
    assert player_state_0.active_playlist_index == 0
    module_1.open_playlist(player_state_0, str_1)


def test_case_22():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    str_0 = "'2 4R\x0cm\x0bzS "
    none_type_0 = module_1.create_playlist(player_state_0, str_0)
    assert len(player_state_0.playlists) == 1
    assert player_state_0.active_playlist_index == 0
    module_1.play_playlist(player_state_0, str_0)


def test_case_23():
    bytes_0 = b"H"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    none_type_0 = module_1.create_playlist(player_state_0, bytes_0)
    assert len(player_state_0.playlists) == 1
    assert player_state_0.active_playlist_index == 0
    none_type_1 = module_1.delete_playlist(player_state_0, bytes_0)
    assert player_state_0.playlists == []
    assert player_state_0.active_playlist_index is None


def test_case_24():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    str_0 = ""
    module_1.create_playlist(player_state_0, str_0)
    module_1.delete_playlist(player_state_0, str_0)


def test_case_25():
    bytes_0 = b"\x93;u*jkL\xe1\x1c\x12b\x9dT?\xf5yG\x1b"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    none_type_0 = module_1.create_playlist(player_state_0, bytes_0)
    assert len(player_state_0.playlists) == 1
    assert player_state_0.active_playlist_index == 0
    str_0 = "){ouu<\x0bwyy\r7o"
    module_1.delete_playlist(player_state_0, str_0)


def test_case_26():
    bytes_0 = b"!\xc0\\<\x94\xff\xec\xe3\x88\xdb\x8a?~\xab\xcd\xee\xbf\xa1\xb8"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.show_current_playlist(player_state_0)
    none_type_0 = None
    player_state_1 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.list_playlists(player_state_1)
    player_state_2 = module_0.PlayerState(bytes_0, none_type_0)
    str_0 = "PdKhob$}+%>NkS}j?Us"
    module_1.open_playlist(player_state_2, str_0)
    str_1 = "WA6882)ka$$-Vu"
    list_0 = []
    player_state_3 = module_0.PlayerState(list_0, str_1)
    str_2 = ""
    module_1.delete_playlist(player_state_3, str_2)


def test_case_27():
    bytes_0 = b"|\xea\xea\xa1G-\xad@!\x1c\xf9"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    str_0 = "8j[T\nt\x0cC=bp^0"
    none_type_0 = module_1.create_playlist(player_state_0, bytes_0)
    assert len(player_state_0.playlists) == 1
    assert player_state_0.active_playlist_index == 0
    module_1.rename_playlist(player_state_0, bytes_0, str_0)


def test_case_28():
    bytes_0 = b"\xf1\xc4\x1d\x0c\xc3L"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    none_type_0 = module_1.create_playlist(player_state_0, bytes_0)
    assert len(player_state_0.playlists) == 1
    assert player_state_0.active_playlist_index == 0
    none_type_1 = module_1.close_playlist(player_state_0)
    assert player_state_0.active_playlist_index is None
    module_1.list_playlists(player_state_0)


def test_case_29():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    str_0 = ""
    module_1.create_playlist(player_state_0, str_0)
    module_1.close_playlist(player_state_0)
    module_1.delete_playlist(player_state_0, str_0)
    module_1.show_current_playlist(player_state_0)


def test_case_30():
    bytes_0 = b"p"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    none_type_0 = module_1.create_playlist(player_state_0, bytes_0)
    assert len(player_state_0.playlists) == 1
    assert player_state_0.active_playlist_index == 0
    str_0 = "]-q90!E[B\rD!\x0c?C`MU"
    none_type_1 = module_1.create_playlist(player_state_0, str_0)
    assert len(player_state_0.playlists) == 2
    none_type_2 = module_1.delete_playlist(player_state_0, bytes_0)
    assert len(player_state_0.playlists) == 1


def test_case_31():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    str_0 = ""
    module_1.delete_playlist(player_state_0, str_0)
    module_1.show_current_playlist(player_state_0)


def test_case_32():
    bytes_0 = b"\xcc\x13\xc5\x83\xb5N"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    str_0 = "5;2|5hT#@Z+j*Z8"
    str_1 = "PlEylis:s: /pl.new /pl.rename /`l.del /pl.listK/pl.open /pl.show /pl.play /pl.?lose /pl.add /pl.remove /pl.move /pl.merge pl.copy"
    none_type_0 = module_1.create_playlist(player_state_0, str_1)
    assert len(player_state_0.playlists) == 1
    assert player_state_0.active_playlist_index == 0
    none_type_1 = module_1.create_playlist(player_state_0, bytes_0)
    assert len(player_state_0.playlists) == 2
    module_1.rename_playlist(player_state_0, bytes_0, str_0)


def test_case_33():
    bytes_0 = b"\xf2\x0e\xb5\x8e"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    str_0 = '0-I^m"PvA?M6g'
    module_1.show_current_playlist(player_state_0)
    none_type_0 = module_1.create_playlist(player_state_0, str_0)
    assert len(player_state_0.playlists) == 1
    assert player_state_0.active_playlist_index == 0
    none_type_1 = module_1.create_playlist(player_state_0, bytes_0)
    assert len(player_state_0.playlists) == 2
    module_1.rename_playlist(player_state_0, bytes_0, str_0)


def test_case_34():
    bytes_0 = b"\xf1\xc4\x1d\x0c\xc3L"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    none_type_0 = module_1.create_playlist(player_state_0, bytes_0)
    assert len(player_state_0.playlists) == 1
    assert player_state_0.active_playlist_index == 0
    module_1.list_playlists(player_state_0)


def test_case_35():
    bytes_0 = b"\x90\xd0\xf3\xb2\xeb\x14f\x91W\x83\xc2\x87\x98.\xf2m\x9c\xe1"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    none_type_0 = module_1.create_playlist(player_state_0, bytes_0)
    assert len(player_state_0.playlists) == 1
    assert player_state_0.active_playlist_index == 0
    str_0 = "*N$alK.d"
    none_type_1 = module_1.create_playlist(player_state_0, str_0)
    assert len(player_state_0.playlists) == 2
    module_1.list_playlists(player_state_0)
