# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
import pytest
import music_player.player_state as module_0
import music_player.player_queue as module_1


@pytest.mark.xfail(strict=True)
# Test: checking that the 'next' track logic correctly rejects broken text input
def test_case_0():
    str_0 = "Ia}khqS"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.next_track(player_state_0)


@pytest.mark.xfail(strict=True)
# Test: verifying that trying to go to the previous track with invalid tab characters causes an error
def test_case_1():
    str_0 = "*qFja;UFu\trIi$;4O8"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.previous_track(player_state_0)


@pytest.mark.xfail(strict=True)
# Test: ensuring the system consistently catches errors when using random text for the player state
def test_case_2():
    str_0 = "Ia}khqS"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.previous_track(player_state_0)


@pytest.mark.xfail(strict=True)
# Test: checking if the previous track handler stays stable when given short, non-standard text
def test_case_3():
    str_0 = "M-h"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.previous_track(player_state_0)


@pytest.mark.xfail(strict=True)
# Test: verifying that the system identifies and rejects track lists that haven't been set up properly
def test_case_4():
    str_0 = "Jjf"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.previous_track(player_state_0)


@pytest.mark.xfail(strict=True)
# Test: checking that the 'next' function handles mixed text and numbers without crashing
def test_case_5():
    str_0 = "lMr?\\w^T%Q4B"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.next_track(player_state_0)


# Test: verifying that skipping backwards on an empty queue doesn't break the system
def test_case_6():
    none_type_0 = None
    list_0 = [none_type_0]
    player_state_0 = module_0.PlayerState(list_0, list_0)
    module_1.previous_track(player_state_0)


@pytest.mark.xfail(strict=True)
# Test: checking the maths for moving backwards through a list of four tracks
def test_case_7():
    str_0 = "n0}Jot5z\rw5+c"
    none_type_0 = None
    list_0 = [str_0, str_0, str_0, none_type_0]
    player_state_0 = module_0.PlayerState(list_0, str_0)
    none_type_1 = module_1.previous_track(player_state_0)
    assert player_state_0.current_index == 3
    module_1.previous_track(player_state_0)


# Test: ensuring that moving forward and then back returns the selection to the original song
def test_case_8():
    none_type_0 = None
    list_0 = [none_type_0]
    player_state_0 = module_0.PlayerState(list_0, list_0)
    module_1.next_track(player_state_0)
    module_1.previous_track(player_state_0)


# Test: verifying that the queue 'wraps around' (skipping back from the start goes to the end, and vice versa)
def test_case_9():
    none_type_0 = None
    list_0 = [none_type_0, none_type_0, none_type_0, none_type_0]
    player_state_0 = module_0.PlayerState(list_0, none_type_0)
    # Backward wrap-around to tail.
    none_type_1 = module_1.previous_track(player_state_0)
    assert player_state_0.current_index == 3
    # Forward wrap-around back to head (Index 0).
    none_type_2 = module_1.next_track(player_state_0)
    assert player_state_0.current_index == 0


@pytest.mark.xfail(strict=True)
# Test: ensuring that the song index doesn't get corrupted after skipping tracks multiple times
def test_case_10():
    str_0 = "n6Sown+#om^ad$ U lp"
    none_type_0 = None
    list_0 = [str_0, str_0, str_0, none_type_0]
    player_state_0 = module_0.PlayerState(list_0, str_0)
    none_type_1 = module_1.previous_track(player_state_0)
    assert player_state_0.current_index == 3
    module_1.next_track(player_state_0)