# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import music_player.player_state as module_0
import music_player.player_ui as module_1


def test_case_0():
    str_0 = ")tA\x0b7lmv"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.print_now_playing(player_state_0)


def test_case_1():
    none_type_0 = None
    player_state_0 = module_0.PlayerState(none_type_0, none_type_0)
    module_1.print_now_playing(player_state_0)


def test_case_2():
    bool_0 = True
    module_1.print_progress(bool_0)


def test_case_3():
    none_type_0 = None
    player_state_0 = module_0.PlayerState(none_type_0, none_type_0)
    module_1.print_progress_bar(player_state_0)
    str_0 = ""
    player_state_1 = module_0.PlayerState(str_0, str_0)
    module_1.print_playlist_with_indicator(player_state_1)


def test_case_4():
    bool_0 = True
    player_state_0 = module_0.PlayerState(bool_0, bool_0)
    module_1.print_playlist_with_indicator(player_state_0)


def test_case_5():
    bool_0 = False
    player_state_0 = module_0.PlayerState(bool_0, bool_0)
    module_1.print_playlist_with_indicator(player_state_0)
    module_1.print_progress(bool_0)


def test_case_6():
    str_0 = "P"
    player_state_0 = module_0.PlayerState(str_0, str_0)
    module_1.print_playlist_with_indicator(player_state_0)
