# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import music_player.playlist_model as module_0
import music_player.library as module_1


def test_case_0():
    str_0 = "9V"
    playlist_0 = module_0.Playlist(str_0)
    assert (
        f"{type(module_0.Playlist.num_tracks).__module__}.{type(module_0.Playlist.num_tracks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_seconds).__module__}.{type(module_0.Playlist.total_duration_seconds).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_mm_ss).__module__}.{type(module_0.Playlist.total_duration_mm_ss).__qualname__}"
        == "builtins.property"
    )
    str_1 = playlist_0.summary_line()
    assert str_1 == "  --  9V                      0 tracks  00:00"


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "5|"
    playlist_0 = module_0.Playlist(str_0, str_0)
    assert (
        f"{type(module_0.Playlist.num_tracks).__module__}.{type(module_0.Playlist.num_tracks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_seconds).__module__}.{type(module_0.Playlist.total_duration_seconds).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_mm_ss).__module__}.{type(module_0.Playlist.total_duration_mm_ss).__qualname__}"
        == "builtins.property"
    )
    playlist_0.summary_line()


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "5|"
    playlist_0 = module_0.Playlist(str_0, str_0)
    assert (
        f"{type(module_0.Playlist.num_tracks).__module__}.{type(module_0.Playlist.num_tracks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_seconds).__module__}.{type(module_0.Playlist.total_duration_seconds).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_mm_ss).__module__}.{type(module_0.Playlist.total_duration_mm_ss).__qualname__}"
        == "builtins.property"
    )
    playlist_0.summary_line(active=playlist_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "5|"
    playlist_0 = module_0.Playlist(str_0, str_0)
    assert (
        f"{type(module_0.Playlist.num_tracks).__module__}.{type(module_0.Playlist.num_tracks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_seconds).__module__}.{type(module_0.Playlist.total_duration_seconds).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_mm_ss).__module__}.{type(module_0.Playlist.total_duration_mm_ss).__qualname__}"
        == "builtins.property"
    )
    var_0 = playlist_0.__eq__(playlist_0)
    playlist_0.summary_line(var_0, str_0)


def test_case_4():
    str_0 = "5|"
    track_0 = module_1.Track(str_0, str_0)
    list_0 = [track_0, track_0]
    playlist_0 = module_0.Playlist(str_0, list_0)
    assert (
        f"{type(module_0.Playlist.num_tracks).__module__}.{type(module_0.Playlist.num_tracks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_seconds).__module__}.{type(module_0.Playlist.total_duration_seconds).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_mm_ss).__module__}.{type(module_0.Playlist.total_duration_mm_ss).__qualname__}"
        == "builtins.property"
    )
    str_1 = playlist_0.summary_line()
    assert str_1 == "  --  5|                      2 tracks  00:00"


@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = ""
    none_type_0 = None
    none_type_1 = None
    track_0 = module_1.Track(none_type_0, none_type_1, duration_seconds=str_0)
    list_0 = [track_0, track_0]
    playlist_0 = module_0.Playlist(str_0, list_0)
    assert (
        f"{type(module_0.Playlist.num_tracks).__module__}.{type(module_0.Playlist.num_tracks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_seconds).__module__}.{type(module_0.Playlist.total_duration_seconds).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Playlist.total_duration_mm_ss).__module__}.{type(module_0.Playlist.total_duration_mm_ss).__qualname__}"
        == "builtins.property"
    )
    playlist_0.summary_line(active=str_0)
