# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import music_player.player_shortcuts as module_0
import music_player.player_state as module_1


def test_case_0():
    float_0 = -1586.54716
    str_0 = "*A"
    module_0.handle_keypress(float_0, str_0)


def test_case_1():
    bool_0 = False
    str_0 = "?5"
    module_0.handle_keypress(bool_0, str_0)


def test_case_2():
    none_type_0 = None
    float_0 = -2250.4931735757023
    player_state_0 = module_1.PlayerState(none_type_0, float_0)
    str_0 = ""
    module_0.handle_keypress(player_state_0, str_0)


def test_case_3():
    none_type_0 = None
    float_0 = -2272.1
    player_state_0 = module_1.PlayerState(none_type_0, float_0)
    str_0 = "=~f!s"
    module_0.handle_keypress(player_state_0, str_0)
