# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import music_player.player_state as module_0
import music_player.player_audio as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    player_state_0 = module_0.PlayerState(bool_0, bool_0)
    module_1.change_volume(player_state_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_1.change_volume(none_type_0, none_type_0)
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    module_1.change_volume(player_state_0, list_0)
    str_0 = "4i@b4G~)\n5=K}"
    module_1.handle_mute_command(player_state_0, str_0)
    module_1.toggle_mute(player_state_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"'\xa8X\xa7"
    player_state_0 = module_0.PlayerState(bytes_0, bytes_0)
    module_1.toggle_mute(player_state_0)


def test_case_3():
    bytes_0 = b"\xd1{g\x8fz\xdb"
    str_0 = "w!r;"
    none_type_0 = module_1.change_volume(bytes_0, str_0)
    module_1.handle_mute_command(str_0, str_0)
    module_1.toggle_mute(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    int_0 = 1131
    module_1.handle_mute_command(int_0, int_0)


def test_case_5():
    none_type_0 = None
    str_0 = "v"
    module_1.handle_mute_command(none_type_0, str_0)
    str_1 = ">qnmSFut"
    player_state_0 = module_0.PlayerState(none_type_0, str_1)
    str_2 = "\n ^ Stopplaback And &ee sison toTX.P\n    SL-01.\n   C"
    str_3 = "O\tx#2\rRB\nN,/tF7Vuq"
    module_1.change_volume(str_2, str_3)
    module_1.handle_mute_command(player_state_0, str_1)


def test_case_6():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    str_0 = "ee"
    module_1.handle_mute_command(player_state_0, str_0)
    module_1.change_volume(player_state_0, list_0)


def test_case_7():
    int_0 = -1132
    bool_0 = True
    str_0 = "\n ^ Stopplaback And &ee sison toTX.P\n    SL-01.\n   C"
    module_1.change_volume(bool_0, int_0)
    float_0 = 3255.514816
    module_1.handle_mute_command(float_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_8():
    int_0 = 2937
    str_0 = "[kK"
    player_state_0 = module_0.PlayerState(int_0, str_0)
    module_1.change_volume(player_state_0, int_0)
    module_1.toggle_mute(player_state_0)


@pytest.mark.xfail(strict=True)
def test_case_9():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    none_type_0 = module_1.change_volume(player_state_0, list_0)
    module_1.toggle_mute(none_type_0)
    module_1.change_volume(player_state_0, player_state_0)


def test_case_10():
    bytes_0 = b"\xd1{g\x8fz\xdb"
    str_0 = "/dvnbUTe"
    module_1.change_volume(bytes_0, str_0)
    module_1.handle_mute_command(str_0, str_0)


def test_case_11():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    str_0 = "GxJ\\S"
    module_1.handle_mute_command(list_0, str_0)
    module_1.change_volume(player_state_0, list_0)


def test_case_12():
    bytes_0 = b"\xd1{g\x8fz\xdb"
    str_0 = "w!r;"
    module_1.change_volume(bytes_0, str_0)
    module_1.handle_mute_command(str_0, str_0)


def test_case_13():
    list_0 = []
    player_state_0 = module_0.PlayerState(list_0, list_0)
    str_0 = "Nf("
    module_1.handle_mute_command(player_state_0, str_0)
