import unittest
from unittest.mock import MagicMock, patch
from music_player.audio_backend import AudioEngine

class TestConcolicExecution(unittest.TestCase):
    """
    Concolic testing suite derived from the Iteration Table.
    Implements the specific concrete seeds generated by flipping path constraints.
    """

    def test_iter1_path_pc1(self):
        """
        Iteration 1: Initial Concrete Seed.
        Inputs: S1=True, S4=True.
        Constraint Collected: S1.
        """
        # Concrete Seed Injection
        with patch('music_player.audio_backend.HAS_PYGAME', True):
            with patch('music_player.audio_backend.pygame') as mock_pygame:
                mock_pygame.mixer.music.get_busy.return_value = True

                player = AudioEngine()
                player.playing = True

                # Verify execution matches the concrete trace
                self.assertTrue(player.is_busy())

    def test_iter2_path_pc2_flip(self):
        """
        Iteration 2: Constraint S1 Flipped to NOT S1.
        Inputs: S1=False, S2=True, S3=False.
        Target: Verify the 'True' branch of the return logic.
        """
        # Concrete Seed Injection
        with patch('music_player.audio_backend.HAS_PYGAME', False):
            player = AudioEngine()
            player.playing = True
            player.paused = False

            # Verify execution matches the derived input logic
            self.assertTrue(player.is_busy())

    def test_iter3_path_pc2_neg(self):
        """
        Iteration 3: Logic Coverage within PC_2.
        Inputs: S1=False, S2=False (or S3=True).
        Target: Verify the 'False' branch of the return logic.
        """
        # Concrete Seed Injection
        with patch('music_player.audio_backend.HAS_PYGAME', False):
            player = AudioEngine()
            player.playing = False
            player.paused = False

            # Verify execution
            self.assertFalse(player.is_busy())


if __name__ == '__main__':
    unittest.main()