"""
Module: player_ui
User Stories:
 - S1-03: see current song title, artist and duration
 - S1-05: see song progress and total time
 - S1-06: see a progress bar
 - S1-10: indicator showing which song is playing in a list
"""
from __future__ import annotations

from typing import Any

from music_player.player_state import PlayerState
from music_player.player_seek import render_progress_bar, get_progress
from music_player.time_utils import format_mm_ss
from music_player.library import Track


def _ensure_player_state(state: Any, context: str) -> PlayerState | None:
    """Internal helper: validate that `state` is a PlayerState.

    If not, print a warning and return None.
    This protects us against nonsense inputs generated by tools like Pynguin.
    """
    if not isinstance(state, PlayerState):
        print(f"[ui] Invalid player state for {context}.")
        return None
    return state


def print_now_playing(state: PlayerState) -> None:
    """
    Print the current song title, artist and duration (S1-03).
    """
    state = _ensure_player_state(state, "now_playing")
    if state is None:
        return

    track = state.current_track
    if not isinstance(track, Track):
        print("[ui] No track selected.")
        return

    duration_str = format_mm_ss(track.duration_seconds)

    if state.is_playing:
        status = "Playing"
    elif state.is_paused:
        status = "Paused"
    else:
        status = "Stopped"

    print(f"[ui] {status}: {track.display_name} [{duration_str}]")


def print_progress(state: PlayerState) -> None:
    """
    Print the song progress and total time (S1-05).
    """
    state = _ensure_player_state(state, "progress")
    if state is None:
        return

    pos, total = get_progress(state)
    print(f"[ui] Progress: {format_mm_ss(pos)}/{format_mm_ss(total)}")


def print_progress_bar(state: PlayerState) -> None:
    """
    Print a textual progress bar for the current track (S1-06).
    """
    state = _ensure_player_state(state, "progress_bar")
    if state is None:
        return

    bar = render_progress_bar(state)
    print(f"[ui] {bar}")


def print_playlist_with_indicator(state: PlayerState) -> None:
    """
    Print the track list with an indicator showing the currently
    active track (S1-10).
    """
    state = _ensure_player_state(state, "playlist")
    if state is None:
        return

    # Ensure tracks is a sequence of Track objects
    tracks = state.tracks
    if not isinstance(tracks, list) or not all(
        isinstance(t, Track) for t in tracks
    ):
        print("[ui] Warning: Library is in an invalid state.")
        return

    if not tracks:
        print("[ui] Warning: Library is empty.")
        return

    # Clamp current_index to a valid range
    if state.current_index < 0:
        state.current_index = 0
    elif state.current_index >= len(tracks):
        state.current_index = len(tracks) - 1

    # Metadata warning
    if any(not t.display_name for t in tracks):
        print("[ui] Warning: Some tracks have missing titles.")

    # Single-track warning
    if len(tracks) == 1:
        print("[ui] Note: Only one track in the library.")

    for idx, track in enumerate(tracks):
        if idx == state.current_index:
            if state.is_playing:
                marker = "▶"
            elif state.is_paused:
                marker = "‖"
            else:
                marker = "•"
        else:
            marker = " "

        print(f"{marker} {idx + 1:02d}: {track.display_name}")